const VOCAB = [
  // Body parts
  { czech: "hlava", english: "head", category: "body" },
  { czech: "krk", english: "neck / throat", category: "body" },
  { czech: "rameno", english: "shoulder", category: "body" },
  { czech: "pravé rameno", english: "right shoulder", category: "body" },
  { czech: "ruka", english: "arm / hand", category: "body" },
  { czech: "noha", english: "leg / foot", category: "body" },
  { czech: "koleno", english: "knee", category: "body" },
  { czech: "levé koleno", english: "left knee", category: "body" },
  { czech: "kotník", english: "ankle", category: "body" },
  { czech: "pravý kotník", english: "right ankle", category: "body" },
  { czech: "záda", english: "back", category: "body" },
  { czech: "břicho", english: "stomach / belly", category: "body" },
  { czech: "srdce", english: "heart", category: "body" },
  { czech: "plíce", english: "lungs", category: "body" },
  { czech: "játra", english: "liver", category: "body" },
  { czech: "ledvina", english: "kidney", category: "body" },
  { czech: "pravá ledvina", english: "right kidney", category: "body" },
  { czech: "mozek", english: "brain", category: "body" },
  { czech: "oko", english: "eye", category: "body" },
  { czech: "ucho", english: "ear", category: "body" },
  { czech: "nos", english: "nose", category: "body" },
  { czech: "ústa", english: "mouth", category: "body" },
  { czech: "zuby", english: "teeth", category: "body" },
  { czech: "prst", english: "finger / toe", category: "body" },
  // Health & medical
  { czech: "céčko", english: "vitamin C", category: "health" },
  { czech: "béčko", english: "vitamin B", category: "health" },
  { czech: "déčko", english: "vitamin D", category: "health" },
  { czech: "éčko", english: "vitamin E", category: "health" },
  { czech: "zinek", english: "zinc", category: "health" },
  { czech: "prášek", english: "pill / powder", category: "health" },
  { czech: "prášky", english: "pills", category: "health" },
  { czech: "brát prášky", english: "to take pills", category: "health" },
  { czech: "fyzioterapeut", english: "physiotherapist", category: "health" },
  { czech: "minerál", english: "mineral", category: "health" },
  { czech: "nemocný", english: "sick / ill", category: "health" },
  { czech: "zdravý", english: "healthy", category: "health" },
  { czech: "bolest", english: "pain", category: "health" },
  { czech: "bolí mě...", english: "my ... hurts", category: "health" },
  { czech: "nachlazení", english: "a cold", category: "health" },
  { czech: "chřipka", english: "flu", category: "health" },
  { czech: "alergie", english: "allergy", category: "health" },
  { czech: "nemocnice", english: "hospital", category: "health" },
  { czech: "lékárna", english: "pharmacy / chemist", category: "health" },
  { czech: "lék", english: "medicine / medication", category: "health" },
  { czech: "recept", english: "prescription", category: "health" },
  { czech: "injekce", english: "injection", category: "health" },
  { czech: "operace", english: "operation", category: "health" },
  { czech: "masáž", english: "massage", category: "health" },
  // Countries & nationalities
  { czech: "Thajsko", english: "Thailand", category: "countries" },
  { czech: "thajský", english: "Thai (adjective)", category: "countries" },
  { czech: "Thajka", english: "Thai woman", category: "countries" },
  { czech: "Indie", english: "India", category: "countries" },
  { czech: "indický", english: "Indian (adjective)", category: "countries" },
  { czech: "Ind", english: "Indian man", category: "countries" },
  { czech: "Indka", english: "Indian woman", category: "countries" },
  { czech: "Mexiko", english: "Mexico", category: "countries" },
  { czech: "mexický", english: "Mexican (adjective)", category: "countries" },
  { czech: "Mexičan", english: "Mexican man", category: "countries" },
  { czech: "Mexičanka", english: "Mexican woman", category: "countries" },
  { czech: "Asie", english: "Asia", category: "countries" },
  { czech: "asijský", english: "Asian (adjective)", category: "countries" },
  { czech: "Itálie", english: "Italy", category: "countries" },
  { czech: "italský", english: "Italian (adjective)", category: "countries" },
  { czech: "Ital", english: "Italian man", category: "countries" },
  { czech: "Italka", english: "Italian woman", category: "countries" },
  { czech: "Francie", english: "France", category: "countries" },
  { czech: "francouzský", english: "French (adjective)", category: "countries" },
  { czech: "Francouz", english: "Frenchman", category: "countries" },
  { czech: "Čína", english: "China", category: "countries" },
  { czech: "čínský", english: "Chinese (adjective)", category: "countries" },
  { czech: "Japonsko", english: "Japan", category: "countries" },
  { czech: "japonský", english: "Japanese (adjective)", category: "countries" },
  { czech: "Španělsko", english: "Spain", category: "countries" },
  { czech: "španělský", english: "Spanish (adjective)", category: "countries" },
  { czech: "Anglie", english: "England", category: "countries" },
  { czech: "anglický", english: "English (adjective)", category: "countries" },
  { czech: "Brit", english: "British man", category: "countries" },
  { czech: "Německo", english: "Germany", category: "countries" },
  { czech: "německý", english: "German (adjective)", category: "countries" },
  { czech: "Němec", english: "German man", category: "countries" },
  // Food & drink
  { czech: "polévka", english: "soup", category: "food" },
  { czech: "česnek", english: "garlic", category: "food" },
  { czech: "pažitka", english: "chives", category: "food" },
  { czech: "kari", english: "curry", category: "food" },
  { czech: "rýže", english: "rice", category: "food" },
  { czech: "špenát", english: "spinach", category: "food" },
  { czech: "fazole", english: "beans", category: "food" },
  { czech: "knedlíky", english: "dumplings", category: "food" },
  { czech: "žebra", english: "ribs", category: "food" },
  { czech: "feferonka", english: "chilli pepper", category: "food" },
  { czech: "hořčice", english: "mustard", category: "food" },
  { czech: "křen", english: "horseradish", category: "food" },
  { czech: "houba", english: "mushroom", category: "food" },
  { czech: "salám", english: "salami", category: "food" },
  { czech: "sýr", english: "cheese", category: "food" },
  { czech: "plněný", english: "stuffed / filled", category: "food" },
  { czech: "kostka", english: "cube", category: "food" },
  { czech: "ostrý", english: "spicy / sharp", category: "food" },
  { czech: "sekaná", english: "meatloaf", category: "food" },
  { czech: "bramborová kaše", english: "mashed potatoes", category: "food" },
  { czech: "hranolky", english: "chips / fries", category: "food" },
  { czech: "vepřové", english: "pork", category: "food" },
  { czech: "hovězí", english: "beef", category: "food" },
  { czech: "kuřecí", english: "chicken (adjective)", category: "food" },
  { czech: "ryba", english: "fish", category: "food" },
  { czech: "zelenina", english: "vegetables", category: "food" },
  { czech: "ovoce", english: "fruit", category: "food" },
  { czech: "chleba", english: "bread", category: "food" },
  { czech: "máslo", english: "butter", category: "food" },
  { czech: "mléko", english: "milk", category: "food" },
  { czech: "vejce", english: "egg", category: "food" },
  { czech: "těstoviny", english: "pasta", category: "food" },
  { czech: "salát", english: "salad", category: "food" },
  { czech: "dezert", english: "dessert", category: "food" },
  { czech: "snídaně", english: "breakfast", category: "food" },
  { czech: "oběd", english: "lunch", category: "food" },
  { czech: "večeře", english: "dinner / supper", category: "food" },
  { czech: "voda", english: "water", category: "food" },
  { czech: "pivo", english: "beer", category: "food" },
  { czech: "víno", english: "wine", category: "food" },
  { czech: "káva", english: "coffee", category: "food" },
  { czech: "čaj", english: "tea", category: "food" },
  { czech: "smažený", english: "fried", category: "food" },
  { czech: "vařený", english: "boiled / cooked", category: "food" },
  { czech: "grilovaný", english: "grilled", category: "food" },
  { czech: "pečený", english: "baked / roasted", category: "food" },
  { czech: "uzený", english: "smoked", category: "food" },
  { czech: "čerstvý", english: "fresh", category: "food" },
  { czech: "sladký", english: "sweet", category: "food" },
  { czech: "kyselý", english: "sour", category: "food" },
  { czech: "slaný", english: "salty", category: "food" },
  { czech: "výborný", english: "excellent / delicious", category: "food" },
  { czech: "chutný", english: "tasty", category: "food" },
  { czech: "restaurace", english: "restaurant", category: "food" },
  { czech: "jídelní lístek", english: "menu", category: "food" },
  { czech: "poledni menu", english: "lunch menu / daily special", category: "food" },
  // Verbs
  { czech: "dívat se", english: "to watch", category: "verbs" },
  { czech: "podívat se", english: "to have a look", category: "verbs" },
  { czech: "brát", english: "to take", category: "verbs" },
  { czech: "vařit", english: "to cook", category: "verbs" },
  { czech: "milovat", english: "to love", category: "verbs" },
  { czech: "mít rád", english: "to like", category: "verbs" },
  { czech: "koupit", english: "to buy (once)", category: "verbs" },
  { czech: "kupovat", english: "to buy (regularly)", category: "verbs" },
  { czech: "nosit", english: "to wear / carry", category: "verbs" },
  { czech: "číst", english: "to read", category: "verbs" },
  { czech: "chodit", english: "to go / attend (regularly)", category: "verbs" },
  { czech: "jít", english: "to go (on foot)", category: "verbs" },
  { czech: "jet", english: "to go (by vehicle)", category: "verbs" },
  { czech: "přijít", english: "to arrive / come", category: "verbs" },
  { czech: "přijet", english: "to arrive (by vehicle)", category: "verbs" },
  { czech: "jíst", english: "to eat", category: "verbs" },
  { czech: "pít", english: "to drink", category: "verbs" },
  { czech: "pracovat", english: "to work", category: "verbs" },
  { czech: "spát", english: "to sleep", category: "verbs" },
  { czech: "vstávat", english: "to get up", category: "verbs" },
  { czech: "chtít", english: "to want", category: "verbs" },
  { czech: "moci", english: "to be able to", category: "verbs" },
  { czech: "muset", english: "to have to / must", category: "verbs" },
  { czech: "mluvit", english: "to speak", category: "verbs" },
  { czech: "psát", english: "to write", category: "verbs" },
  { czech: "doporučit", english: "to recommend", category: "verbs" },
  { czech: "cítit se", english: "to feel", category: "verbs" },
  // Phrases
  { czech: "Kolik je hodin?", english: "What time is it?", category: "phrases" },
  { czech: "V kolik hodin?", english: "At what time?", category: "phrases" },
  { czech: "Co ho bolí?", english: "What is hurting him?", category: "phrases" },
  { czech: "Bolí mě záda.", english: "My back hurts.", category: "phrases" },
  { czech: "Bolí mě hlava.", english: "I have a headache.", category: "phrases" },
  { czech: "Kde tě bolí?", english: "Where does it hurt?", category: "phrases" },
  { czech: "Kde jsi byl?", english: "Where were you?", category: "phrases" },
  { czech: "U doktora.", english: "At the doctor's.", category: "phrases" },
  { czech: "K doktorovi.", english: "To the doctor's.", category: "phrases" },
  { czech: "Jsi nemocný?", english: "Are you sick?", category: "phrases" },
  { czech: "Jak to?", english: "How so? / How come?", category: "phrases" },
  { czech: "Jak se cítíš?", english: "How do you feel?", category: "phrases" },
  { czech: "Cítím se špatně.", english: "I feel bad.", category: "phrases" },
  { czech: "Mám nachlazení.", english: "I have a cold.", category: "phrases" },
  { czech: "Mám chřipku.", english: "I have the flu.", category: "phrases" },
  { czech: "Nejradši mám...", english: "I like ... best.", category: "phrases" },
  { czech: "Máš rád...?", english: "Do you like...?", category: "phrases" },
  { czech: "Máš hlad?", english: "Are you hungry?", category: "phrases" },
  { czech: "Mám hlad.", english: "I'm hungry.", category: "phrases" },
  { czech: "Mám žízeň.", english: "I'm thirsty.", category: "phrases" },
  { czech: "Jíš to často?", english: "Do you eat it often?", category: "phrases" },
  { czech: "Dám si...", english: "I'll have... (ordering food)", category: "phrases" },
  { czech: "Co doporučujete?", english: "What do you recommend?", category: "phrases" },
  { czech: "Jak chutná?", english: "How does it taste?", category: "phrases" },
  { czech: "Je to výborné.", english: "It's excellent.", category: "phrases" },
  { czech: "Je to moc ostré.", english: "It's too spicy.", category: "phrases" },
  { czech: "Účet prosím.", english: "The bill please.", category: "phrases" },
  { czech: "Každý den.", english: "Every day.", category: "phrases" },
  { czech: "Za 2 týdny.", english: "In 2 weeks.", category: "phrases" },
  { czech: "To máš dobře!", english: "That's good for you!", category: "phrases" },
  { czech: "Všechno je v pořádku.", english: "Everything is OK.", category: "phrases" },
  { czech: "Blízko nás", english: "Close to us / nearby", category: "phrases" },
  { czech: "Ještě ne.", english: "Not yet.", category: "phrases" },
  { czech: "Hned.", english: "Right away.", category: "phrases" },
  { czech: "Doufám, že...", english: "I hope that...", category: "phrases" },
  { czech: "Myslím, že...", english: "I think that...", category: "phrases" },
  { czech: "Vypadá to, že...", english: "It looks like...", category: "phrases" },
  // Time
  { czech: "půl deváté", english: "8:30 (half past eight)", category: "time" },
  { czech: "půl osmé", english: "7:30 (half past seven)", category: "time" },
  { czech: "datum", english: "date", category: "time" },
  { czech: "čas", english: "time", category: "time" },
  { czech: "ráno", english: "in the morning", category: "time" },
  { czech: "dopoledne", english: "in the late morning", category: "time" },
  { czech: "odpoledne", english: "in the afternoon", category: "time" },
  { czech: "večer", english: "in the evening", category: "time" },
  { czech: "v noci", english: "at night", category: "time" },
  { czech: "dnes", english: "today", category: "time" },
  { czech: "včera", english: "yesterday", category: "time" },
  { czech: "zítra", english: "tomorrow", category: "time" },
  { czech: "tento týden", english: "this week", category: "time" },
  { czech: "příští týden", english: "next week", category: "time" },
  { czech: "minulý týden", english: "last week", category: "time" },
  { czech: "vždy", english: "always", category: "time" },
  { czech: "někdy", english: "sometimes", category: "time" },
  { czech: "nikdy", english: "never", category: "time" },
  { czech: "teď", english: "now", category: "time" },
  { czech: "brzy", english: "soon", category: "time" },
  { czech: "potom", english: "afterwards / later", category: "time" },
  // Plurals
  { czech: "doktoři", english: "doctors (m)", category: "plurals" },
  { czech: "lékaři", english: "doctors / physicians (m, formal)", category: "plurals" },
  { czech: "bratři", english: "brothers", category: "plurals" },
  { czech: "sestry", english: "sisters", category: "plurals" },
  { czech: "auta", english: "cars", category: "plurals" },
  { czech: "obědy", english: "lunches", category: "plurals" },
  { czech: "ženy", english: "women", category: "plurals" },
  { czech: "muži", english: "men", category: "plurals" },
  { czech: "děti", english: "children", category: "plurals" },
  { czech: "přátelé", english: "friends", category: "plurals" },
  { czech: "studenti", english: "students (m)", category: "plurals" },
  { czech: "učitelé", english: "teachers (m)", category: "plurals" },
  { czech: "restaurace", english: "restaurants", category: "plurals" },
  { czech: "prášky", english: "pills / tablets", category: "plurals" },
  // Past tense forms (m = male speaker, f = female speaker)
  { czech: "byl / byla", english: "was (m / f)", category: "past_tense" },
  { czech: "měl / měla", english: "had (m / f)", category: "past_tense" },
  { czech: "šel / šla", english: "went — on foot (m / f)", category: "past_tense" },
  { czech: "jel / jela", english: "went — by vehicle (m / f)", category: "past_tense" },
  { czech: "jedl / jedla", english: "ate (m / f)", category: "past_tense" },
  { czech: "pil / pila", english: "drank (m / f)", category: "past_tense" },
  { czech: "chtěl / chtěla", english: "wanted (m / f)", category: "past_tense" },
  { czech: "mohl / mohla", english: "could (m / f)", category: "past_tense" },
  { czech: "musel / musela", english: "had to (m / f)", category: "past_tense" },
  { czech: "viděl / viděla", english: "saw (m / f)", category: "past_tense" },
  { czech: "slyšel / slyšela", english: "heard (m / f)", category: "past_tense" },
  { czech: "četl / četla", english: "read (m / f)", category: "past_tense" },
  { czech: "psal / psala", english: "wrote (m / f)", category: "past_tense" },
  { czech: "vařil / vařila", english: "cooked (m / f)", category: "past_tense" },
  { czech: "mluvil / mluvila", english: "spoke (m / f)", category: "past_tense" },
  { czech: "pracoval / pracovala", english: "worked (m / f)", category: "past_tense" },
  { czech: "dělal / dělala", english: "did / made (m / f)", category: "past_tense" },
  { czech: "přišel / přišla", english: "arrived — on foot (m / f)", category: "past_tense" },
  { czech: "přijel / přijela", english: "arrived — by vehicle (m / f)", category: "past_tense" },
  { czech: "byl jsem / byla jsem", english: "I was (m / f speaker)", category: "past_tense" },
  { czech: "šel jsem / šla jsem", english: "I went — on foot (m / f speaker)", category: "past_tense" },
  { czech: "viděl jsem / viděla jsem", english: "I saw (m / f speaker)", category: "past_tense" },
  { czech: "Kde jsi byl/a?", english: "Where were you? (m / f)", category: "past_tense" },
  { czech: "Co jsi dělal/a?", english: "What were you doing? (m / f)", category: "past_tense" },
  { czech: "Byl/a jsi tam?", english: "Were you there? (m / f)", category: "past_tense" },
  { czech: "Ještě jsem to neudělal/a.", english: "I haven't done it yet. (m / f)", category: "past_tense" },
  // Cases & prepositions
  { czech: "do + gen.", english: "into / to — do knihovny (to the library)", category: "cases" },
  { czech: "z / ze + gen.", english: "from / out of — z práce (from work)", category: "cases" },
  { czech: "u + gen.", english: "at (someone's place) — u doktora (at the doctor's)", category: "cases" },
  { czech: "bez + gen.", english: "without — bez cukru (without sugar)", category: "cases" },
  { czech: "od + gen.", english: "from — od pondělí (from Monday)", category: "cases" },
  { czech: "v / ve + loc.", english: "in — v restauraci (in the restaurant)", category: "cases" },
  { czech: "na + loc.", english: "on / at (place) — na masáži (at the massage)", category: "cases" },
  { czech: "o + loc.", english: "about — o doktorovi (about the doctor)", category: "cases" },
  { czech: "k / ke + dat.", english: "to / towards — k doktorovi (to the doctor)", category: "cases" },
  { czech: "na + acc.", english: "onto / towards (direction) — na televizi (onto the TV)", category: "cases" },
  { czech: "pro + acc.", english: "for — pro mě (for me)", category: "cases" },
  { czech: "přes + acc.", english: "across / through — přes park (through the park)", category: "cases" },
  { czech: "s / se + inst.", english: "with — s máslem (with butter)", category: "cases" },
  // Adjective agreement (m / f / n)
  { czech: "dobrý / dobrá / dobré", english: "good (m / f / n)", category: "adjectives" },
  { czech: "velký / velká / velké", english: "big (m / f / n)", category: "adjectives" },
  { czech: "malý / malá / malé", english: "small (m / f / n)", category: "adjectives" },
  { czech: "nový / nová / nové", english: "new (m / f / n)", category: "adjectives" },
  { czech: "starý / stará / staré", english: "old (m / f / n)", category: "adjectives" },
  { czech: "hezký / hezká / hezké", english: "nice / pretty (m / f / n)", category: "adjectives" },
  { czech: "unavený / unavená / unavené", english: "tired (m / f / n)", category: "adjectives" },
  { czech: "šťastný / šťastná / šťastné", english: "happy (m / f / n)", category: "adjectives" },
  { czech: "drahý / drahá / drahé", english: "expensive (m / f / n)", category: "adjectives" },
  { czech: "levný / levná / levné", english: "cheap (m / f / n)", category: "adjectives" },
  { czech: "rychlý / rychlá / rychlé", english: "fast / quick (m / f / n)", category: "adjectives" },
  { czech: "pomalý / pomalá / pomalé", english: "slow (m / f / n)", category: "adjectives" },
  { czech: "zajímavý / zajímavá / zajímavé", english: "interesting (m / f / n)", category: "adjectives" },
  { czech: "nudný / nudná / nudné", english: "boring (m / f / n)", category: "adjectives" },
  { czech: "český / česká / české", english: "Czech (m / f / n)", category: "adjectives" },
  { czech: "horký / horká / horké", english: "hot (m / f / n)", category: "adjectives" },
  { czech: "studený / studená / studené", english: "cold (m / f / n)", category: "adjectives" },
  // Verb aspect pairs (perfective / imperfective)
  { czech: "koupit / kupovat", english: "to buy — once / habitually", category: "aspect" },
  { czech: "přijít / přicházet", english: "to arrive (foot) — once / regularly", category: "aspect" },
  { czech: "odejít / odcházet", english: "to leave (foot) — once / regularly", category: "aspect" },
  { czech: "uvařit / vařit", english: "to cook — once / regularly", category: "aspect" },
  { czech: "napsat / psát", english: "to write — once / regularly", category: "aspect" },
  { czech: "přečíst / číst", english: "to read (through) — once / regularly", category: "aspect" },
  { czech: "udělat / dělat", english: "to do/make — once / regularly", category: "aspect" },
  { czech: "zavolat / volat", english: "to call — once / regularly", category: "aspect" },
  { czech: "dát / dávat", english: "to give — once / regularly", category: "aspect" },
  { czech: "říct / říkat", english: "to say — once / regularly", category: "aspect" },
  { czech: "vzít / brát", english: "to take — once / regularly", category: "aspect" },
  { czech: "podívat se / dívat se", english: "to have a look / to watch — once / regularly", category: "aspect" },
  { czech: "sníst / jíst", english: "to eat (up) — once / regularly", category: "aspect" },
  { czech: "vypít / pít", english: "to drink (up) — once / regularly", category: "aspect" },
  // Connectors
  { czech: "ale", english: "but", category: "connectors" },
  { czech: "protože", english: "because", category: "connectors" },
  { czech: "proto", english: "therefore / that's why", category: "connectors" },
  { czech: "tak", english: "so / then", category: "connectors" },
  { czech: "když", english: "when / if", category: "connectors" },
  { czech: "že", english: "that (conjunction — myslím, že...)", category: "connectors" },
  { czech: "také / taky", english: "also / too", category: "connectors" },
  { czech: "nebo", english: "or", category: "connectors" },
  { czech: "ani", english: "nor / not even", category: "connectors" },
  { czech: "aby", english: "so that / in order to", category: "connectors" },
  { czech: "přestože", english: "although / even though", category: "connectors" },
  { czech: "pokud", english: "if / provided that", category: "connectors" },
  { czech: "než", english: "than / before (time)", category: "connectors" },
  { czech: "jak", english: "how / as / like", category: "connectors" },
  { czech: "a", english: "and", category: "connectors" },
  { czech: "proto že → protože", english: "that's why → because (common confusion)", category: "connectors" },
  // Negation
  { czech: "nikdy", english: "never", category: "negation" },
  { czech: "nic", english: "nothing", category: "negation" },
  { czech: "nikde", english: "nowhere (place)", category: "negation" },
  { czech: "nikam", english: "nowhere (direction)", category: "negation" },
  { czech: "nikdo", english: "nobody", category: "negation" },
  { czech: "žádný / žádná / žádné", english: "no / none / not any (m / f / n)", category: "negation" },
  { czech: "vůbec ne", english: "not at all", category: "negation" },
  { czech: "ne- (prefix)", english: "negates any verb: nejím, nevím, nejdu, nemám", category: "negation" },
  { czech: "nejím", english: "I don't eat", category: "negation" },
  { czech: "nevím", english: "I don't know", category: "negation" },
  { czech: "nejdu", english: "I'm not going", category: "negation" },
  { czech: "nemám", english: "I don't have", category: "negation" },
  { czech: "nechci", english: "I don't want", category: "negation" },
  { czech: "Nikdy nic nejím.", english: "I never eat anything. (double negation — correct in Czech)", category: "negation" },
  { czech: "Chtěl/a bych...", english: "I would like... (m / f) — polite request", category: "negation" },
];

const MATCHING_SETS = [
  {
    title: "Lesson 1 — Food & Health",
    pairs: [
      { q: "Co jste měli včera k večeři?", a: "Kuřecí kostky na kari a rýži." },
      { q: "Kdy bude Martin zpátky?", a: "Za 2 týdny." },
      { q: "Máš rád polévky?", a: "Mám. Nejradši mám česneku." },
      { q: "Bereš nějaké vitamíny?", a: "Ano. Céčko a béčko." },
      { q: "Kde je Ivana?", a: "Na masáži." },
      { q: "Bolí ho něco?", a: "Ne. Všechno je v pořádku." },
    ]
  },
  {
    title: "Lesson 2 — Questions & Places",
    pairs: [
      { q: "Bereš nějaké vitamíny?", a: "Jo. Vitamín C a vitamín B12." },
      { q: "Máš rád pažitku?", a: "Jo. Miluji chleba s máslem a pažitkou." },
      { q: "Jakou vaříš polévku?", a: "Česneku." },
      { q: "Kde jsi byl?", a: "Na masáži." },
      { q: "Kam jdeš?", a: "Do knihovny." },
      { q: "Jak dlouho jste byli pryč?", a: "2 týdny." },
      { q: "Kdy budeš doma?", a: "V 18:45." },
    ]
  },
  {
    title: "Lesson 3 — School & Doctor",
    pairs: [
      { q: "Kde je Milan?", a: "U doktora." },
      { q: "Kam jdeš?", a: "K doktorovi." },
      { q: "Napsal jsi ten dopis?", a: "Ještě ne. Udělám to zítra." },
      { q: "Nosí Ivan brýle?", a: "Jo. Nosí. Na čtení." },
      { q: "Co bude k večeři?", a: "Sekaná a bramborová kaše." },
      { q: "Co teď čteš?", a: "Psychologický román." },
      { q: "Chodí Michal na základní školu?", a: "Na střední." },
      { q: "Kdy přijedou vaši?", a: "23. 4." },
    ]
  },
  {
    title: "Lesson 4 — Watching TV",
    pairs: [
      { q: "Na co se díváš?", a: "Na francouzskou komedii." },
      { q: "Chceš se večer dívat na televizi?", a: "Dneska ne. Budu si číst." },
      { q: "Máme doma céčko?", a: "Myslím, že ano. Podívám se." },
      { q: "Kde je Michal?", a: "U doktora." },
    ]
  },
  {
    title: "Lesson 5 — Health & Body",
    pairs: [
      { q: "Kde tě bolí?", a: "Bolí mě záda." },
      { q: "Co ti je?", a: "Mám nachlazení." },
      { q: "Jak se cítíš?", a: "Cítím se špatně." },
      { q: "Byl jsi u doktora?", a: "Ano. Dal mi recept." },
      { q: "Bereš nějaké léky?", a: "Jo. Beru prášky na bolest." },
      { q: "Kdy budeš zdravý?", a: "Doufám, že brzy." },
    ]
  },
  {
    title: "Lesson 6 — Restaurant & Food",
    pairs: [
      { q: "Máš hlad?", a: "Ano, mám. Kdy jíme?" },
      { q: "Co si dáš?", a: "Dám si kuřecí polévku." },
      { q: "Jak chutná?", a: "Je to výborné!" },
      { q: "Je to moc ostré?", a: "Ne, je to akorát." },
      { q: "Co doporučujete?", a: "Doporučuji grilovaná žebra." },
      { q: "Účet prosím.", a: "Samozřejmě, hned." },
    ]
  },
  {
    title: "Lesson 7 — Past Tense",
    pairs: [
      { q: "Co jsi měl/a k obědu?", a: "Měl jsem kuřecí polévku." },
      { q: "Kde jsi byl včera večer?", a: "Byl jsem v restauraci." },
      { q: "Viděl jsi ten film?", a: "Ne, ještě jsem ho neviděl." },
      { q: "Kdy jsi přišel domů?", a: "Přišel jsem ve 20:00." },
      { q: "Co jste dělali o víkendu?", a: "Šli jsme na procházku." },
      { q: "Mluvil jsi česky?", a: "Ano, trochu jsem mluvil." },
    ]
  },
  {
    title: "Lesson 8 — Connectors & Negation",
    pairs: [
      { q: "Proč nejdeš do práce?", a: "Protože jsem nemocný." },
      { q: "Chceš kávu nebo čaj?", a: "Ani jedno, díky." },
      { q: "Jíš maso?", a: "Ne, nikdy nejím maso." },
      { q: "Víš, kde je Michal?", a: "Nevím. Nikde ho nevidím." },
      { q: "Máš hlad?", a: "Vůbec ne. Právě jsem jedl." },
      { q: "Proč to neuděláš?", a: "Protože nemám čas." },
    ]
  },
];

const CONJUGATIONS = [
  {
    verb: "dívat se",
    english: "to watch",
    forms: [
      { pronoun: "já", form: "dívám se", english: "I watch" },
      { pronoun: "ty", form: "díváš se", english: "you watch" },
      { pronoun: "on/ona", form: "dívá se", english: "he/she watches" },
      { pronoun: "my", form: "díváme se", english: "we watch" },
      { pronoun: "vy", form: "díváte se", english: "you (pl) watch" },
      { pronoun: "oni", form: "dívají se", english: "they watch" },
    ]
  },
  {
    verb: "brát",
    english: "to take",
    forms: [
      { pronoun: "já", form: "beru", english: "I take" },
      { pronoun: "ty", form: "bereš", english: "you take" },
      { pronoun: "on/ona", form: "bere", english: "he/she takes" },
      { pronoun: "my", form: "bereme", english: "we take" },
      { pronoun: "vy", form: "berete", english: "you (pl) take" },
      { pronoun: "oni", form: "berou", english: "they take" },
    ]
  },
  {
    verb: "jít",
    english: "to go (on foot)",
    forms: [
      { pronoun: "já", form: "jdu", english: "I go" },
      { pronoun: "ty", form: "jdeš", english: "you go" },
      { pronoun: "on/ona", form: "jde", english: "he/she goes" },
      { pronoun: "my", form: "jdeme", english: "we go" },
      { pronoun: "vy", form: "jdete", english: "you (pl) go" },
      { pronoun: "oni", form: "jdou", english: "they go" },
    ]
  },
  {
    verb: "mít",
    english: "to have",
    forms: [
      { pronoun: "já", form: "mám", english: "I have" },
      { pronoun: "ty", form: "máš", english: "you have" },
      { pronoun: "on/ona", form: "má", english: "he/she has" },
      { pronoun: "my", form: "máme", english: "we have" },
      { pronoun: "vy", form: "máte", english: "you (pl) have" },
      { pronoun: "oni", form: "mají", english: "they have" },
    ]
  },
  {
    verb: "chtít",
    english: "to want",
    forms: [
      { pronoun: "já", form: "chci", english: "I want" },
      { pronoun: "ty", form: "chceš", english: "you want" },
      { pronoun: "on/ona", form: "chce", english: "he/she wants" },
      { pronoun: "my", form: "chceme", english: "we want" },
      { pronoun: "vy", form: "chcete", english: "you (pl) want" },
      { pronoun: "oni", form: "chtějí", english: "they want" },
    ]
  },
  {
    verb: "jíst",
    english: "to eat",
    forms: [
      { pronoun: "já", form: "jím", english: "I eat" },
      { pronoun: "ty", form: "jíš", english: "you eat" },
      { pronoun: "on/ona", form: "jí", english: "he/she eats" },
      { pronoun: "my", form: "jíme", english: "we eat" },
      { pronoun: "vy", form: "jíte", english: "you (pl) eat" },
      { pronoun: "oni", form: "jedí", english: "they eat" },
    ]
  },
  {
    verb: "být",
    english: "to be (present)",
    forms: [
      { pronoun: "já", form: "jsem", english: "I am" },
      { pronoun: "ty", form: "jsi", english: "you are" },
      { pronoun: "on/ona", form: "je", english: "he/she is" },
      { pronoun: "my", form: "jsme", english: "we are" },
      { pronoun: "vy", form: "jste", english: "you (pl) are" },
      { pronoun: "oni", form: "jsou", english: "they are" },
    ]
  },
  {
    verb: "dělat — past tense (male speaker)",
    english: "to do / make (past, male)",
    forms: [
      { pronoun: "já", form: "dělal jsem", english: "I did / was doing" },
      { pronoun: "ty", form: "dělal jsi", english: "you did" },
      { pronoun: "on", form: "dělal", english: "he did (no auxiliary)" },
      { pronoun: "my", form: "dělali jsme", english: "we did" },
      { pronoun: "vy", form: "dělali jste", english: "you (pl) did" },
      { pronoun: "oni", form: "dělali", english: "they did (no auxiliary)" },
    ]
  },
  {
    verb: "dělat — past tense (female speaker)",
    english: "to do / make (past, female)",
    forms: [
      { pronoun: "já", form: "dělala jsem", english: "I did / was doing" },
      { pronoun: "ty", form: "dělala jsi", english: "you did" },
      { pronoun: "ona", form: "dělala", english: "she did (no auxiliary)" },
      { pronoun: "my", form: "dělaly jsme", english: "we did" },
      { pronoun: "vy", form: "dělaly jste", english: "you (pl) did" },
      { pronoun: "ony", form: "dělaly", english: "they did (no auxiliary)" },
    ]
  },
  {
    verb: "být — past tense",
    english: "to be (past)",
    forms: [
      { pronoun: "já (m)", form: "byl jsem", english: "I was (male)" },
      { pronoun: "já (f)", form: "byla jsem", english: "I was (female)" },
      { pronoun: "ty (m)", form: "byl jsi", english: "you were (male)" },
      { pronoun: "on/ona", form: "byl / byla", english: "he was / she was" },
      { pronoun: "my", form: "byli / byly jsme", english: "we were (m / f)" },
      { pronoun: "oni", form: "byli / byly", english: "they were (m / f)" },
    ]
  },
];
