const VOCAB = [
  // Body parts
  { czech: "hlava", english: "head", category: "body" },
  { czech: "krk", english: "neck / throat", category: "body" },
  { czech: "rameno", english: "shoulder", category: "body" },
  { czech: "pravé rameno", english: "right shoulder", category: "body" },
  { czech: "ruka", english: "arm / hand", category: "body" },
  { czech: "noha", english: "leg / foot", category: "body" },
  { czech: "koleno", english: "knee", category: "body" },
  { czech: "levé koleno", english: "left knee", category: "body" },
  { czech: "kotník", english: "ankle", category: "body" },
  { czech: "pravý kotník", english: "right ankle", category: "body" },
  { czech: "záda", english: "back", category: "body" },
  { czech: "břicho", english: "stomach / belly", category: "body" },
  { czech: "srdce", english: "heart", category: "body" },
  { czech: "plíce", english: "lungs", category: "body" },
  { czech: "játra", english: "liver", category: "body" },
  { czech: "ledvina", english: "kidney", category: "body" },
  { czech: "pravá ledvina", english: "right kidney", category: "body" },
  { czech: "mozek", english: "brain", category: "body" },
  { czech: "oko", english: "eye", category: "body" },
  { czech: "ucho", english: "ear", category: "body" },
  { czech: "nos", english: "nose", category: "body" },
  { czech: "ústa", english: "mouth", category: "body" },
  { czech: "zuby", english: "teeth", category: "body" },
  { czech: "prst", english: "finger / toe", category: "body" },
  // Appearance & facial features
  { czech: "vlasy", english: "hair", category: "body" },
  { czech: "vousy", english: "beard / facial hair", category: "body" },
  { czech: "knír", english: "moustache", category: "body" },
  { czech: "účes", english: "hairstyle / hairdo", category: "body" },
  { czech: "obočí", english: "eyebrow / eyebrows", category: "body" },
  { czech: "řasa / řasy", english: "eyelash / eyelashes", category: "body" },
  { czech: "piha / pihy", english: "freckle / freckles", category: "body" },
  { czech: "pleš", english: "bald patch", category: "body" },
  { czech: "pleť", english: "complexion / skin tone", category: "body" },
  { czech: "sval / svaly", english: "muscle / muscles", category: "body" },
  { czech: "tělo", english: "body (whole)", category: "body" },
  { czech: "pusa", english: "mouth / kiss", category: "body" },
  { czech: "ret / rty", english: "lip / lips", category: "body" },
  { czech: "čelo", english: "forehead", category: "body" },
  { czech: "vrásek / vrásky", english: "wrinkle / wrinkles", category: "body" },
  { czech: "loket / lokty", english: "elbow / elbows", category: "body" },
  { czech: "pata", english: "heel", category: "body" },
  { czech: "postava", english: "figure / physique", category: "body" },
  { czech: "povaha", english: "character / personality", category: "body" },
  { czech: "žaludek", english: "stomach (organ)", category: "body" },
  { czech: "střevo / střeva", english: "intestine / intestines", category: "body" },
  { czech: "zápěstí", english: "wrist", category: "body" },
  // Health & medical
  { czech: "céčko", english: "vitamin C", category: "health" },
  { czech: "béčko", english: "vitamin B", category: "health" },
  { czech: "déčko", english: "vitamin D", category: "health" },
  { czech: "éčko", english: "vitamin E", category: "health" },
  { czech: "zinek", english: "zinc", category: "health" },
  { czech: "prášek", english: "pill / powder", category: "health" },
  { czech: "prášky", english: "pills", category: "health" },
  { czech: "brát prášky", english: "to take pills", category: "health" },
  { czech: "fyzioterapeut", english: "physiotherapist", category: "health" },
  { czech: "minerál", english: "mineral", category: "health" },
  { czech: "nemocný", english: "sick / ill", category: "health" },
  { czech: "zdravý", english: "healthy", category: "health" },
  { czech: "bolest", english: "pain", category: "health" },
  { czech: "bolí mě...", english: "my ... hurts", category: "health" },
  { czech: "nachlazení", english: "a cold", category: "health" },
  { czech: "chřipka", english: "flu", category: "health" },
  { czech: "alergie", english: "allergy", category: "health" },
  { czech: "nemocnice", english: "hospital", category: "health" },
  { czech: "lékárna", english: "pharmacy / chemist", category: "health" },
  { czech: "lék", english: "medicine / medication", category: "health" },
  { czech: "recept", english: "prescription", category: "health" },
  { czech: "injekce", english: "injection", category: "health" },
  { czech: "operace", english: "operation", category: "health" },
  { czech: "masáž", english: "massage", category: "health" },
  { czech: "lékař / lékařka", english: "doctor (m / f)", category: "health" },
  { czech: "chirurg", english: "surgeon", category: "health" },
  { czech: "zubař / zubařka", english: "dentist (m / f)", category: "health" },
  { czech: "pacient / pacientka", english: "patient (m / f)", category: "health" },
  // Hygiene & bathroom
  { czech: "bylina / bylinka", english: "herb / herbal plant", category: "health" },
  { czech: "bylinkový", english: "herbal (adjective)", category: "health" },
  { czech: "mýdlo", english: "soap", category: "health" },
  { czech: "šampon", english: "shampoo", category: "health" },
  { czech: "kondicionér", english: "conditioner", category: "health" },
  { czech: "zubní pasta", english: "toothpaste", category: "health" },
  { czech: "zubní kartáček", english: "toothbrush", category: "health" },
  { czech: "hřeben", english: "comb", category: "health" },
  { czech: "umyvadlo", english: "washbasin / sink", category: "health" },
  { czech: "sprcha", english: "shower", category: "health" },
  { czech: "sprchový gel", english: "shower gel", category: "health" },
  { czech: "krém", english: "cream / lotion", category: "health" },
  { czech: "brýle", english: "glasses / spectacles", category: "health" },
  { czech: "cigareta", english: "cigarette", category: "health" },
  { czech: "tabák", english: "tobacco", category: "health" },
  { czech: "kuřák / kuřačka", english: "smoker (m / f)", category: "health" },
  { czech: "nekuřák / nekuřačka", english: "non-smoker (m / f)", category: "health" },
  // Countries & nationalities
  { czech: "Thajsko", english: "Thailand", category: "countries" },
  { czech: "thajský", english: "Thai (adjective)", category: "countries" },
  { czech: "Thajka", english: "Thai woman", category: "countries" },
  { czech: "Indie", english: "India", category: "countries" },
  { czech: "indický", english: "Indian (adjective)", category: "countries" },
  { czech: "Ind", english: "Indian man", category: "countries" },
  { czech: "Indka", english: "Indian woman", category: "countries" },
  { czech: "Mexiko", english: "Mexico", category: "countries" },
  { czech: "mexický", english: "Mexican (adjective)", category: "countries" },
  { czech: "Mexičan", english: "Mexican man", category: "countries" },
  { czech: "Mexičanka", english: "Mexican woman", category: "countries" },
  { czech: "Asie", english: "Asia", category: "countries" },
  { czech: "asijský", english: "Asian (adjective)", category: "countries" },
  { czech: "Itálie", english: "Italy", category: "countries" },
  { czech: "italský", english: "Italian (adjective)", category: "countries" },
  { czech: "Ital", english: "Italian man", category: "countries" },
  { czech: "Italka", english: "Italian woman", category: "countries" },
  { czech: "Francie", english: "France", category: "countries" },
  { czech: "francouzský", english: "French (adjective)", category: "countries" },
  { czech: "Francouz", english: "Frenchman", category: "countries" },
  { czech: "Čína", english: "China", category: "countries" },
  { czech: "čínský", english: "Chinese (adjective)", category: "countries" },
  { czech: "Japonsko", english: "Japan", category: "countries" },
  { czech: "japonský", english: "Japanese (adjective)", category: "countries" },
  { czech: "Španělsko", english: "Spain", category: "countries" },
  { czech: "španělský", english: "Spanish (adjective)", category: "countries" },
  { czech: "Anglie", english: "England", category: "countries" },
  { czech: "anglický", english: "English (adjective)", category: "countries" },
  { czech: "Brit", english: "British man", category: "countries" },
  { czech: "Německo", english: "Germany", category: "countries" },
  { czech: "německý", english: "German (adjective)", category: "countries" },
  { czech: "Němec", english: "German man", category: "countries" },
  { czech: "Evropa", english: "Europe", category: "countries" },
  { czech: "v Evropě", english: "in Europe", category: "countries" },
  { czech: "Amerika", english: "America", category: "countries" },
  { czech: "v Americe", english: "in America", category: "countries" },
  { czech: "Řecko", english: "Greece", category: "countries" },
  { czech: "řecký", english: "Greek (adjective)", category: "countries" },
  { czech: "Rusko", english: "Russia", category: "countries" },
  { czech: "Polsko", english: "Poland", category: "countries" },
  { czech: "Belgie", english: "Belgium", category: "countries" },
  { czech: "Rakousko", english: "Austria", category: "countries" },
  { czech: "Irsko", english: "Ireland", category: "countries" },
  { czech: "Dánsko", english: "Denmark", category: "countries" },
  { czech: "Norsko", english: "Norway", category: "countries" },
  { czech: "Nizozemsko", english: "Netherlands", category: "countries" },
  { czech: "Turecko", english: "Turkey", category: "countries" },
  { czech: "Maďarsko", english: "Hungary", category: "countries" },
  { czech: "Chorvatsko", english: "Croatia", category: "countries" },
  { czech: "Rumunsko", english: "Romania", category: "countries" },
  { czech: "Bulharsko", english: "Bulgaria", category: "countries" },
  { czech: "Slovensko", english: "Slovakia", category: "countries" },
  { czech: "Slovinsko", english: "Slovenia", category: "countries" },
  { czech: "Švédsko", english: "Sweden", category: "countries" },
  { czech: "Švýcarsko", english: "Switzerland", category: "countries" },
  { czech: "Portugalsko", english: "Portugal", category: "countries" },
  { czech: "Ukrajina", english: "Ukraine", category: "countries" },
  { czech: "Velká Británie", english: "Great Britain", category: "countries" },
  // Food & drink
  { czech: "polévka", english: "soup", category: "food" },
  { czech: "česnek", english: "garlic", category: "food" },
  { czech: "pažitka", english: "chives", category: "food" },
  { czech: "kari", english: "curry", category: "food" },
  { czech: "rýže", english: "rice", category: "food" },
  { czech: "špenát", english: "spinach", category: "food" },
  { czech: "fazole", english: "beans", category: "food" },
  { czech: "knedlíky", english: "dumplings", category: "food" },
  { czech: "žebra", english: "ribs", category: "food" },
  { czech: "feferonka", english: "chilli pepper", category: "food" },
  { czech: "hořčice", english: "mustard", category: "food" },
  { czech: "křen", english: "horseradish", category: "food" },
  { czech: "houba", english: "mushroom", category: "food" },
  { czech: "salám", english: "salami", category: "food" },
  { czech: "sýr", english: "cheese", category: "food" },
  { czech: "plněný", english: "stuffed / filled", category: "food" },
  { czech: "kostka", english: "cube", category: "food" },
  { czech: "ostrý", english: "spicy / sharp", category: "food" },
  { czech: "sekaná", english: "meatloaf", category: "food" },
  { czech: "bramborová kaše", english: "mashed potatoes", category: "food" },
  { czech: "hranolky", english: "chips / fries", category: "food" },
  { czech: "vepřové", english: "pork", category: "food" },
  { czech: "hovězí", english: "beef", category: "food" },
  { czech: "kuřecí", english: "chicken (adjective)", category: "food" },
  { czech: "ryba", english: "fish", category: "food" },
  { czech: "zelenina", english: "vegetables", category: "food" },
  { czech: "ovoce", english: "fruit", category: "food" },
  { czech: "chleba", english: "bread", category: "food" },
  { czech: "máslo", english: "butter", category: "food" },
  { czech: "mléko", english: "milk", category: "food" },
  { czech: "vejce", english: "egg", category: "food" },
  { czech: "těstoviny", english: "pasta", category: "food" },
  { czech: "salát", english: "salad", category: "food" },
  { czech: "dezert", english: "dessert", category: "food" },
  { czech: "snídaně", english: "breakfast", category: "food" },
  { czech: "oběd", english: "lunch", category: "food" },
  { czech: "večeře", english: "dinner / supper", category: "food" },
  { czech: "voda", english: "water", category: "food" },
  { czech: "pivo", english: "beer", category: "food" },
  { czech: "víno", english: "wine", category: "food" },
  { czech: "káva", english: "coffee", category: "food" },
  { czech: "čaj", english: "tea", category: "food" },
  { czech: "smažený", english: "fried", category: "food" },
  { czech: "vařený", english: "boiled / cooked", category: "food" },
  { czech: "grilovaný", english: "grilled", category: "food" },
  { czech: "pečený", english: "baked / roasted", category: "food" },
  { czech: "uzený", english: "smoked", category: "food" },
  { czech: "čerstvý", english: "fresh", category: "food" },
  { czech: "sladký", english: "sweet", category: "food" },
  { czech: "kyselý", english: "sour", category: "food" },
  { czech: "slaný", english: "salty", category: "food" },
  { czech: "výborný", english: "excellent / delicious", category: "food" },
  { czech: "chutný", english: "tasty", category: "food" },
  { czech: "restaurace", english: "restaurant", category: "food" },
  { czech: "jídelní lístek", english: "menu", category: "food" },
  { czech: "polední menu", english: "lunch menu / daily special", category: "food" },
  // More food & drink from lessons
  { czech: "brambory", english: "potatoes", category: "food" },
  { czech: "mrkev", english: "carrot", category: "food" },
  { czech: "pór", english: "leek", category: "food" },
  { czech: "máta", english: "mint", category: "food" },
  { czech: "heřmánek", english: "camomile", category: "food" },
  { czech: "citron", english: "lemon", category: "food" },
  { czech: "jahoda", english: "strawberry", category: "food" },
  { czech: "borůvka", english: "blueberry", category: "food" },
  { czech: "tvaroh", english: "cottage cheese / curd", category: "food" },
  { czech: "bílek", english: "egg white", category: "food" },
  { czech: "žloutek", english: "egg yolk", category: "food" },
  { czech: "kapr", english: "carp", category: "food" },
  { czech: "celer", english: "celery", category: "food" },
  { czech: "oliva", english: "olive", category: "food" },
  { czech: "chřest", english: "asparagus", category: "food" },
  { czech: "pikantní", english: "spicy / piquant", category: "food" },
  { czech: "bramborový knedlík", english: "potato dumpling", category: "food" },
  { czech: "houskový knedlík", english: "bread dumpling", category: "food" },
  { czech: "ovocný knedlík", english: "fruit dumpling", category: "food" },
  { czech: "svařené víno", english: "mulled wine", category: "food" },
  { czech: "placka", english: "flatbread / corn pancake", category: "food" },
  { czech: "jahodový džem", english: "strawberry jam", category: "food" },
  { czech: "nudle", english: "noodles", category: "food" },
  { czech: "žampion", english: "champignon / mushroom", category: "food" },
  { czech: "pepř", english: "pepper (spice)", category: "food" },
  { czech: "omáčka", english: "sauce / gravy", category: "food" },
  { czech: "houbová omáčka", english: "mushroom sauce", category: "food" },
  { czech: "jasmínová rýže", english: "jasmine rice", category: "food" },
  { czech: "marinovaný", english: "marinated", category: "food" },
  { czech: "vepřový steak", english: "pork steak", category: "food" },
  // Fish
  { czech: "losos", english: "salmon", category: "food" },
  { czech: "makrela", english: "mackerel", category: "food" },
  { czech: "sardinka", english: "sardine", category: "food" },
  { czech: "treska", english: "cod", category: "food" },
  // Fruit & nuts
  { czech: "broskev", english: "peach", category: "food" },
  { czech: "nektarinka", english: "nectarine", category: "food" },
  { czech: "fíky", english: "figs", category: "food" },
  { czech: "datle", english: "dates", category: "food" },
  { czech: "mango", english: "mango", category: "food" },
  { czech: "kokos", english: "coconut", category: "food" },
  { czech: "mandle", english: "almond", category: "food" },
  { czech: "pistácie", english: "pistachio", category: "food" },
  { czech: "kešu", english: "cashew", category: "food" },
  { czech: "arašídy", english: "peanuts", category: "food" },
  { czech: "vlašské ořechy", english: "walnuts", category: "food" },
  // Grains & bread
  { czech: "pšenice", english: "wheat", category: "food" },
  { czech: "žito", english: "rye", category: "food" },
  { czech: "strouhanka", english: "breadcrumbs", category: "food" },
  { czech: "celozrnný", english: "wholegrain", category: "food" },
  // Spices & herbs
  { czech: "koření", english: "spices", category: "food" },
  { czech: "surovina", english: "ingredient", category: "food" },
  { czech: "oregano", english: "oregano", category: "food" },
  { czech: "bazalka", english: "basil", category: "food" },
  { czech: "zázvor", english: "ginger", category: "food" },
  { czech: "majoránka", english: "marjoram", category: "food" },
  { czech: "kopr", english: "dill", category: "food" },
  { czech: "škorice", english: "cinnamon", category: "food" },
  { czech: "vanilka", english: "vanilla", category: "food" },
  { czech: "hřebíček", english: "clove", category: "food" },
  { czech: "kmín", english: "caraway seeds", category: "food" },
  { czech: "kurkuma", english: "turmeric", category: "food" },
  { czech: "muškát", english: "nutmeg", category: "food" },
  // Vegetables & legumes
  { czech: "lilek / baklažán", english: "aubergine / eggplant", category: "food" },
  { czech: "cuketa", english: "courgette / zucchini", category: "food" },
  { czech: "zelené fazole", english: "green beans", category: "food" },
  // Game & specialty meats
  { czech: "zvěřina", english: "game / venison", category: "food" },
  { czech: "skopové", english: "mutton", category: "food" },
  { czech: "jehněčí", english: "lamb", category: "food" },
  { czech: "telecí", english: "veal", category: "food" },
  { czech: "paštika", english: "pâté", category: "food" },
  { czech: "kýta", english: "leg / haunch (meat cut)", category: "food" },
  { czech: "steak", english: "steak", category: "food" },
  { czech: "pečivo", english: "baked goods / bread rolls", category: "food" },
  // Other food
  { czech: "feta", english: "feta cheese", category: "food" },
  { czech: "perník", english: "gingerbread", category: "food" },
  { czech: "cukroví", english: "Christmas sweets / cookies", category: "food" },
  { czech: "šípek", english: "rosehip", category: "food" },
  { czech: "brusinky", english: "cranberries", category: "food" },
  { czech: "horká čokoláda", english: "hot chocolate", category: "food" },
  { czech: "vídeňská káva", english: "Viennese coffee", category: "food" },
  { czech: "suchý", english: "dry", category: "food" },
  { czech: "sušený", english: "dried", category: "food" },
  { czech: "mokrý", english: "wet", category: "food" },
  { czech: "komedie", english: "comedy", category: "phrases" },
  // Verbs
  { czech: "dívat se", english: "to watch", category: "verbs" },
  { czech: "podívat se", english: "to have a look", category: "verbs" },
  { czech: "brát", english: "to take", category: "verbs" },
  { czech: "vařit", english: "to cook", category: "verbs" },
  { czech: "milovat", english: "to love", category: "verbs" },
  { czech: "mít rád", english: "to like", category: "verbs" },
  { czech: "koupit", english: "to buy (once)", category: "verbs" },
  { czech: "kupovat", english: "to buy (regularly)", category: "verbs" },
  { czech: "nosit", english: "to wear / carry", category: "verbs" },
  { czech: "číst", english: "to read", category: "verbs" },
  { czech: "chodit", english: "to go / attend (regularly)", category: "verbs" },
  { czech: "jít", english: "to go (on foot)", category: "verbs" },
  { czech: "jet", english: "to go (by vehicle)", category: "verbs" },
  { czech: "přijít", english: "to arrive / come", category: "verbs" },
  { czech: "přijet", english: "to arrive (by vehicle)", category: "verbs" },
  { czech: "jíst", english: "to eat", category: "verbs" },
  { czech: "pít", english: "to drink", category: "verbs" },
  { czech: "pracovat", english: "to work", category: "verbs" },
  { czech: "spát", english: "to sleep", category: "verbs" },
  { czech: "vstávat", english: "to get up", category: "verbs" },
  { czech: "chtít", english: "to want", category: "verbs" },
  { czech: "moci", english: "to be able to", category: "verbs" },
  { czech: "muset", english: "to have to / must", category: "verbs" },
  { czech: "mluvit", english: "to speak", category: "verbs" },
  { czech: "psát", english: "to write", category: "verbs" },
  { czech: "doporučit", english: "to recommend", category: "verbs" },
  { czech: "cítit se", english: "to feel", category: "verbs" },
  // More verbs from lessons
  { czech: "holit se", english: "to shave", category: "verbs" },
  { czech: "oholit se", english: "to have a shave (completed)", category: "verbs" },
  { czech: "sprchovat se", english: "to shower (regularly)", category: "verbs" },
  { czech: "osprchovat se", english: "to have a shower (once)", category: "verbs" },
  { czech: "opalovat se", english: "to sunbathe", category: "verbs" },
  { czech: "cvičit", english: "to exercise", category: "verbs" },
  { czech: "pomáhat", english: "to help", category: "verbs" },
  { czech: "gratulovat", english: "to congratulate", category: "verbs" },
  { czech: "sedět", english: "to sit", category: "verbs" },
  { czech: "žít", english: "to live", category: "verbs" },
  { czech: "cestovat", english: "to travel", category: "verbs" },
  { czech: "rezervovat", english: "to book / reserve", category: "verbs" },
  { czech: "stárnout", english: "to get older / age", category: "verbs" },
  { czech: "ptát se", english: "to ask", category: "verbs" },
  { czech: "zapomenout", english: "to forget", category: "verbs" },
  { czech: "vzpomenout si", english: "to remember", category: "verbs" },
  { czech: "odpovědět", english: "to answer / reply", category: "verbs" },
  { czech: "potkat", english: "to meet / run into", category: "verbs" },
  { czech: "zaplatit", english: "to pay", category: "verbs" },
  { czech: "vydělávat", english: "to earn (money)", category: "verbs" },
  { czech: "usmívat se", english: "to smile (regularly)", category: "verbs" },
  { czech: "usmát se", english: "to smile (once)", category: "verbs" },
  { czech: "surfovat", english: "to surf", category: "verbs" },
  { czech: "plavat", english: "to swim", category: "verbs" },
  { czech: "běhat", english: "to run", category: "verbs" },
  { czech: "uklízet", english: "to clean / tidy up", category: "verbs" },
  { czech: "prát", english: "to do laundry / wash clothes", category: "verbs" },
  { czech: "zavírat", english: "to close (regularly)", category: "verbs" },
  { czech: "zavřít", english: "to close (once)", category: "verbs" },
  { czech: "přestávat", english: "to stop (regularly)", category: "verbs" },
  { czech: "přestat", english: "to stop (once)", category: "verbs" },
  { czech: "utrácet", english: "to spend money (regularly)", category: "verbs" },
  { czech: "utratit", english: "to spend money (once)", category: "verbs" },
  { czech: "bydlet", english: "to live / reside", category: "verbs" },
  { czech: "umět", english: "to know how to", category: "verbs" },
  { czech: "znát", english: "to know (a person / place)", category: "verbs" },
  { czech: "vědět", english: "to know (a fact)", category: "verbs" },
  { czech: "spěchat", english: "to hurry / be in a hurry", category: "verbs" },
  { czech: "sportovat", english: "to do sport / exercise", category: "verbs" },
  { czech: "strouhat", english: "to grate (regularly)", category: "verbs" },
  { czech: "nastrouhat", english: "to grate (completed)", category: "verbs" },
  { czech: "řešit", english: "to solve (regularly)", category: "verbs" },
  { czech: "vyřešit", english: "to solve (completed)", category: "verbs" },
  { czech: "poslouchat", english: "to listen (to)", category: "verbs" },
  { czech: "potkat se", english: "to meet up (with someone)", category: "verbs" },
  // Phrases
  { czech: "Kolik je hodin?", english: "What time is it?", category: "phrases" },
  { czech: "V kolik hodin?", english: "At what time?", category: "phrases" },
  { czech: "Co ho bolí?", english: "What is hurting him?", category: "phrases" },
  { czech: "Bolí mě záda.", english: "My back hurts.", category: "phrases" },
  { czech: "Bolí mě hlava.", english: "I have a headache.", category: "phrases" },
  { czech: "Kde tě bolí?", english: "Where does it hurt?", category: "phrases" },
  { czech: "Kde jsi byl?", english: "Where were you?", category: "phrases" },
  { czech: "U doktora.", english: "At the doctor's.", category: "phrases" },
  { czech: "K doktorovi.", english: "To the doctor's.", category: "phrases" },
  { czech: "Jsi nemocný?", english: "Are you sick?", category: "phrases" },
  { czech: "Jak to?", english: "How so? / How come?", category: "phrases" },
  { czech: "Jak se cítíš?", english: "How do you feel?", category: "phrases" },
  { czech: "Cítím se špatně.", english: "I feel bad.", category: "phrases" },
  { czech: "Mám nachlazení.", english: "I have a cold.", category: "phrases" },
  { czech: "Mám chřipku.", english: "I have the flu.", category: "phrases" },
  { czech: "Nejradši mám...", english: "I like ... best.", category: "phrases" },
  { czech: "Máš rád...?", english: "Do you like...?", category: "phrases" },
  { czech: "Máš hlad?", english: "Are you hungry?", category: "phrases" },
  { czech: "Mám hlad.", english: "I'm hungry.", category: "phrases" },
  { czech: "Mám žízeň.", english: "I'm thirsty.", category: "phrases" },
  { czech: "Jíš to často?", english: "Do you eat it often?", category: "phrases" },
  { czech: "Dám si...", english: "I'll have... (ordering food)", category: "phrases" },
  { czech: "Co doporučujete?", english: "What do you recommend?", category: "phrases" },
  { czech: "Jak chutná?", english: "How does it taste?", category: "phrases" },
  { czech: "Je to výborné.", english: "It's excellent.", category: "phrases" },
  { czech: "Je to moc ostré.", english: "It's too spicy.", category: "phrases" },
  { czech: "Účet prosím.", english: "The bill please.", category: "phrases" },
  { czech: "Každý den.", english: "Every day.", category: "phrases" },
  { czech: "Za 2 týdny.", english: "In 2 weeks.", category: "phrases" },
  { czech: "To máš dobře!", english: "That's good for you!", category: "phrases" },
  { czech: "Všechno je v pořádku.", english: "Everything is OK.", category: "phrases" },
  { czech: "Blízko nás", english: "Close to us / nearby", category: "phrases" },
  { czech: "Ještě ne.", english: "Not yet.", category: "phrases" },
  { czech: "Hned.", english: "Right away.", category: "phrases" },
  { czech: "Doufám, že...", english: "I hope that...", category: "phrases" },
  { czech: "Myslím, že...", english: "I think that...", category: "phrases" },
  { czech: "Vypadá to, že...", english: "It looks like...", category: "phrases" },
  // More phrases from lessons
  { czech: "Šťastnou cestu!", english: "Have a good journey! / Bon voyage!", category: "phrases" },
  { czech: "Dej mi pusu.", english: "Give me a kiss.", category: "phrases" },
  { czech: "Jak vypadám?", english: "How do I look?", category: "phrases" },
  { czech: "To je ostuda.", english: "That's a shame.", category: "phrases" },
  { czech: "Moc se těším.", english: "I'm really looking forward to it.", category: "phrases" },
  { czech: "Kdo je na řadě?", english: "Who is next?", category: "phrases" },
  { czech: "Jak to jde?", english: "How is it going?", category: "phrases" },
  { czech: "Stojí to moc peněz.", english: "It costs a lot of money.", category: "phrases" },
  { czech: "Mám novou práci.", english: "I have a new job.", category: "phrases" },
  // Nouns — general
  { czech: "věc / věci", english: "thing / things", category: "phrases" },
  { czech: "hvězda", english: "star", category: "phrases" },
  { czech: "úsměv", english: "smile", category: "phrases" },
  { czech: "ostuda", english: "shame", category: "phrases" },
  { czech: "zákazník / zákaznice", english: "customer (m / f)", category: "phrases" },
  { czech: "prodavač / prodavačka", english: "shop assistant (m / f)", category: "phrases" },
  { czech: "odpověď", english: "answer / reply", category: "phrases" },
  { czech: "otázka", english: "question", category: "phrases" },
  { czech: "ticho", english: "quiet / silence", category: "phrases" },
  { czech: "dálnice", english: "highway / motorway", category: "phrases" },
  { czech: "rezervace", english: "reservation / booking", category: "phrases" },
  { czech: "výhled", english: "view", category: "phrases" },
  { czech: "dveře", english: "door", category: "phrases" },
  { czech: "okno / okna", english: "window / windows", category: "phrases" },
  { czech: "benzin", english: "petrol / gasoline", category: "phrases" },
  { czech: "tělocvična", english: "gym / sports hall", category: "phrases" },
  { czech: "hodinky", english: "watch (wristwatch)", category: "phrases" },
  { czech: "baterie / baterka", english: "battery / torch", category: "phrases" },
  { czech: "dáma", english: "lady", category: "phrases" },
  // Clothing
  { czech: "boty / obuv", english: "shoes / footwear", category: "phrases" },
  { czech: "ponožky", english: "socks", category: "phrases" },
  { czech: "podkolenky", english: "knee-high socks", category: "phrases" },
  { czech: "sandály", english: "sandals", category: "phrases" },
  { czech: "papuče", english: "slippers", category: "phrases" },
  { czech: "šála", english: "scarf", category: "phrases" },
  { czech: "čepice", english: "hat / cap", category: "phrases" },
  { czech: "rukavice", english: "gloves", category: "phrases" },
  { czech: "sako", english: "jacket / blazer", category: "phrases" },
  { czech: "prádlo", english: "underwear / laundry", category: "phrases" },
  { czech: "pračka", english: "washing machine", category: "phrases" },
  // Animals
  { czech: "zvíře / zvířata", english: "animal / animals", category: "phrases" },
  { czech: "hmyz", english: "insects", category: "phrases" },
  { czech: "pavouk", english: "spider", category: "phrases" },
  { czech: "had", english: "snake", category: "phrases" },
  { czech: "moucha", english: "fly (insect)", category: "phrases" },
  { czech: "komár", english: "mosquito", category: "phrases" },
  { czech: "vosa", english: "wasp", category: "phrases" },
  { czech: "včela", english: "bee", category: "phrases" },
  { czech: "krokodýl", english: "crocodile", category: "phrases" },
  { czech: "slon", english: "elephant", category: "phrases" },
  { czech: "žirafa", english: "giraffe", category: "phrases" },
  { czech: "klokan", english: "kangaroo", category: "phrases" },
  { czech: "opice", english: "monkey / ape", category: "phrases" },
  { czech: "osel", english: "donkey", category: "phrases" },
  { czech: "lev", english: "lion", category: "phrases" },
  { czech: "medvěd", english: "bear", category: "phrases" },
  { czech: "ovce", english: "sheep", category: "phrases" },
  { czech: "koza", english: "goat", category: "phrases" },
  { czech: "morče", english: "guinea pig", category: "phrases" },
  { czech: "kotě", english: "kitten", category: "phrases" },
  { czech: "kráva", english: "cow", category: "phrases" },
  { czech: "želva", english: "tortoise / turtle", category: "phrases" },
  { czech: "farma", english: "farm", category: "phrases" },
  // Flowers & trees
  { czech: "tulipán", english: "tulip", category: "phrases" },
  { czech: "růže", english: "rose", category: "phrases" },
  { czech: "orchidej", english: "orchid", category: "phrases" },
  { czech: "karafiát", english: "carnation", category: "phrases" },
  { czech: "slunečnice", english: "sunflower", category: "phrases" },
  { czech: "jabloň", english: "apple tree", category: "phrases" },
  { czech: "hrušeň", english: "pear tree", category: "phrases" },
  { czech: "švestka", english: "plum / plum tree", category: "phrases" },
  { czech: "třešeň", english: "cherry tree (sweet)", category: "phrases" },
  { czech: "višeň", english: "cherry tree (sour)", category: "phrases" },
  // Misc nouns
  { czech: "zrcadlo", english: "mirror", category: "phrases" },
  { czech: "bankovka", english: "banknote", category: "phrases" },
  { czech: "mince", english: "coin", category: "phrases" },
  { czech: "cena", english: "price / prize", category: "phrases" },
  { czech: "sen", english: "dream", category: "phrases" },
  { czech: "galerie", english: "gallery", category: "phrases" },
  { czech: "muzeum", english: "museum", category: "phrases" },
  { czech: "aktivita", english: "activity", category: "phrases" },
  { czech: "spolu", english: "together", category: "phrases" },
  { czech: "spolubydlící", english: "flatmate / roommate", category: "phrases" },
  { czech: "spolužák / spolužačka", english: "classmate (m / f)", category: "phrases" },
  { czech: "národ", english: "nation / people", category: "phrases" },
  { czech: "národní", english: "national", category: "phrases" },
  { czech: "to nevadí", english: "it doesn't matter / never mind", category: "phrases" },
  { czech: "prázdniny", english: "holidays / school break", category: "phrases" },
  { czech: "chata", english: "cottage / chalet", category: "phrases" },
  { czech: "uvnitř", english: "inside", category: "phrases" },
  { czech: "les", english: "forest / woods", category: "phrases" },
  { czech: "silnice", english: "road", category: "phrases" },
  { czech: "výstava", english: "exhibition", category: "phrases" },
  { czech: "jinam", english: "somewhere else (direction)", category: "phrases" },
  { czech: "rohožka", english: "doormat", category: "phrases" },
  // Time
  { czech: "půl deváté", english: "8:30 (half past eight)", category: "time" },
  { czech: "půl osmé", english: "7:30 (half past seven)", category: "time" },
  { czech: "datum", english: "date", category: "time" },
  { czech: "čas", english: "time", category: "time" },
  { czech: "ráno", english: "in the morning", category: "time" },
  { czech: "dopoledne", english: "in the late morning", category: "time" },
  { czech: "odpoledne", english: "in the afternoon", category: "time" },
  { czech: "večer", english: "in the evening", category: "time" },
  { czech: "v noci", english: "at night", category: "time" },
  { czech: "dnes", english: "today", category: "time" },
  { czech: "včera", english: "yesterday", category: "time" },
  { czech: "zítra", english: "tomorrow", category: "time" },
  { czech: "tento týden", english: "this week", category: "time" },
  { czech: "příští týden", english: "next week", category: "time" },
  { czech: "minulý týden", english: "last week", category: "time" },
  { czech: "vždy", english: "always", category: "time" },
  { czech: "někdy", english: "sometimes", category: "time" },
  { czech: "nikdy", english: "never", category: "time" },
  { czech: "teď", english: "now", category: "time" },
  { czech: "brzy", english: "soon", category: "time" },
  { czech: "potom", english: "afterwards / later", category: "time" },
  // Time — seasons, frequency & directions
  { czech: "zima", english: "winter", category: "time" },
  { czech: "leden", english: "January", category: "time" },
  { czech: "tentokrát", english: "this time", category: "time" },
  { czech: "většinou", english: "most of the time", category: "time" },
  { czech: "každý", english: "every / each", category: "time" },
  { czech: "každý druhý den", english: "every other day", category: "time" },
  { czech: "sever", english: "north", category: "time" },
  { czech: "jih", english: "south", category: "time" },
  { czech: "východ", english: "east", category: "time" },
  { czech: "západ", english: "west", category: "time" },
  { czech: "na sever", english: "to the north / northwards", category: "time" },
  { czech: "na jih", english: "to the south / southwards", category: "time" },
  { czech: "na východ", english: "to the east / eastwards", category: "time" },
  { czech: "na západ", english: "to the west / westwards", category: "time" },
  { czech: "někam", english: "somewhere", category: "time" },
  { czech: "sekunda", english: "second (unit of time)", category: "time" },
  // Plurals
  { czech: "doktoři", english: "doctors (m)", category: "plurals" },
  { czech: "lékaři", english: "doctors / physicians (m, formal)", category: "plurals" },
  { czech: "bratři", english: "brothers", category: "plurals" },
  { czech: "sestry", english: "sisters", category: "plurals" },
  { czech: "auta", english: "cars", category: "plurals" },
  { czech: "obědy", english: "lunches", category: "plurals" },
  { czech: "ženy", english: "women", category: "plurals" },
  { czech: "muži", english: "men", category: "plurals" },
  { czech: "děti", english: "children", category: "plurals" },
  { czech: "přátelé", english: "friends", category: "plurals" },
  { czech: "studenti", english: "students (m)", category: "plurals" },
  { czech: "učitelé", english: "teachers (m)", category: "plurals" },
  { czech: "restaurace", english: "restaurants", category: "plurals" },
  { czech: "prášky", english: "pills / tablets", category: "plurals" },
  { czech: "sourozenec / sourozenci", english: "sibling / siblings", category: "plurals" },
  { czech: "peníze", english: "money (always plural in Czech)", category: "plurals" },
  // Past tense forms (m = male speaker, f = female speaker)
  { czech: "byl / byla", english: "was (m / f)", category: "past_tense" },
  { czech: "měl / měla", english: "had (m / f)", category: "past_tense" },
  { czech: "šel / šla", english: "went — on foot (m / f)", category: "past_tense" },
  { czech: "jel / jela", english: "went — by vehicle (m / f)", category: "past_tense" },
  { czech: "jedl / jedla", english: "ate (m / f)", category: "past_tense" },
  { czech: "pil / pila", english: "drank (m / f)", category: "past_tense" },
  { czech: "chtěl / chtěla", english: "wanted (m / f)", category: "past_tense" },
  { czech: "mohl / mohla", english: "could (m / f)", category: "past_tense" },
  { czech: "musel / musela", english: "had to (m / f)", category: "past_tense" },
  { czech: "viděl / viděla", english: "saw (m / f)", category: "past_tense" },
  { czech: "slyšel / slyšela", english: "heard (m / f)", category: "past_tense" },
  { czech: "četl / četla", english: "read (m / f)", category: "past_tense" },
  { czech: "psal / psala", english: "wrote (m / f)", category: "past_tense" },
  { czech: "vařil / vařila", english: "cooked (m / f)", category: "past_tense" },
  { czech: "mluvil / mluvila", english: "spoke (m / f)", category: "past_tense" },
  { czech: "pracoval / pracovala", english: "worked (m / f)", category: "past_tense" },
  { czech: "dělal / dělala", english: "did / made (m / f)", category: "past_tense" },
  { czech: "přišel / přišla", english: "arrived — on foot (m / f)", category: "past_tense" },
  { czech: "přijel / přijela", english: "arrived — by vehicle (m / f)", category: "past_tense" },
  { czech: "byl jsem / byla jsem", english: "I was (m / f speaker)", category: "past_tense" },
  { czech: "šel jsem / šla jsem", english: "I went — on foot (m / f speaker)", category: "past_tense" },
  { czech: "viděl jsem / viděla jsem", english: "I saw (m / f speaker)", category: "past_tense" },
  { czech: "Kde jsi byl/a?", english: "Where were you? (m / f)", category: "past_tense" },
  { czech: "Co jsi dělal/a?", english: "What were you doing? (m / f)", category: "past_tense" },
  { czech: "Byl/a jsi tam?", english: "Were you there? (m / f)", category: "past_tense" },
  { czech: "Ještě jsem to neudělal/a.", english: "I haven't done it yet. (m / f)", category: "past_tense" },
  // Cases & prepositions
  { czech: "do + gen.", english: "into / to — do knihovny (to the library)", category: "cases" },
  { czech: "z / ze + gen.", english: "from / out of — z práce (from work)", category: "cases" },
  { czech: "u + gen.", english: "at (someone's place) — u doktora (at the doctor's)", category: "cases" },
  { czech: "bez + gen.", english: "without — bez cukru (without sugar)", category: "cases" },
  { czech: "od + gen.", english: "from — od pondělí (from Monday)", category: "cases" },
  { czech: "v / ve + loc.", english: "in — v restauraci (in the restaurant)", category: "cases" },
  { czech: "na + loc.", english: "on / at (place) — na masáži (at the massage)", category: "cases" },
  { czech: "o + loc.", english: "about — o doktorovi (about the doctor)", category: "cases" },
  { czech: "k / ke + dat.", english: "to / towards — k doktorovi (to the doctor)", category: "cases" },
  { czech: "na + acc.", english: "onto / towards (direction) — na televizi (onto the TV)", category: "cases" },
  { czech: "pro + acc.", english: "for — pro mě (for me)", category: "cases" },
  { czech: "přes + acc.", english: "across / through — přes park (through the park)", category: "cases" },
  { czech: "s / se + inst.", english: "with — s máslem (with butter)", category: "cases" },
  // Adjective agreement (m / f / n)
  { czech: "dobrý / dobrá / dobré", english: "good (m / f / n)", category: "adjectives" },
  { czech: "velký / velká / velké", english: "big (m / f / n)", category: "adjectives" },
  { czech: "malý / malá / malé", english: "small (m / f / n)", category: "adjectives" },
  { czech: "nový / nová / nové", english: "new (m / f / n)", category: "adjectives" },
  { czech: "starý / stará / staré", english: "old (m / f / n)", category: "adjectives" },
  { czech: "hezký / hezká / hezké", english: "nice / pretty (m / f / n)", category: "adjectives" },
  { czech: "unavený / unavená / unavené", english: "tired (m / f / n)", category: "adjectives" },
  { czech: "šťastný / šťastná / šťastné", english: "happy (m / f / n)", category: "adjectives" },
  { czech: "drahý / drahá / drahé", english: "expensive (m / f / n)", category: "adjectives" },
  { czech: "levný / levná / levné", english: "cheap (m / f / n)", category: "adjectives" },
  { czech: "rychlý / rychlá / rychlé", english: "fast / quick (m / f / n)", category: "adjectives" },
  { czech: "pomalý / pomalá / pomalé", english: "slow (m / f / n)", category: "adjectives" },
  { czech: "zajímavý / zajímavá / zajímavé", english: "interesting (m / f / n)", category: "adjectives" },
  { czech: "nudný / nudná / nudné", english: "boring (m / f / n)", category: "adjectives" },
  { czech: "český / česká / české", english: "Czech (m / f / n)", category: "adjectives" },
  { czech: "horký / horká / horké", english: "hot (m / f / n)", category: "adjectives" },
  { czech: "studený / studená / studené", english: "cold (m / f / n)", category: "adjectives" },
  // More adjectives from lessons
  { czech: "hladký / hladká / hladké", english: "smooth (m / f / n)", category: "adjectives" },
  { czech: "oholený / oholená", english: "shaved / clean-shaven (m / f)", category: "adjectives" },
  { czech: "opálený / opálená / opálené", english: "tanned (m / f / n)", category: "adjectives" },
  { czech: "spálený / spálená / spálené", english: "sunburnt (m / f / n)", category: "adjectives" },
  { czech: "frustrující", english: "frustrating", category: "adjectives" },
  { czech: "frustrovaný / frustrovaná", english: "frustrated (m / f)", category: "adjectives" },
  { czech: "hodný / hodná / hodné", english: "kind / nice (m / f / n)", category: "adjectives" },
  { czech: "štíhlý / štíhlá / štíhlé", english: "slim (m / f / n)", category: "adjectives" },
  { czech: "opravený / opravená", english: "fixed / repaired (m / f)", category: "adjectives" },
  { czech: "připravený / připravená", english: "ready (m / f)", category: "adjectives" },
  { czech: "vystresovaný / vystresovaná", english: "stressed (m / f)", category: "adjectives" },
  { czech: "stejný / stejná / stejné", english: "same (m / f / n)", category: "adjectives" },
  { czech: "pravý / pravá / pravé", english: "right (m / f / n)", category: "adjectives" },
  { czech: "levý / levá / levé", english: "left (m / f / n)", category: "adjectives" },
  { czech: "plešatý / plešatá", english: "bald (m / f)", category: "adjectives" },
  { czech: "špatný / horší / nejhorší", english: "bad / worse / worst", category: "adjectives" },
  { czech: "velký / větší / největší", english: "big / bigger / biggest", category: "adjectives" },
  { czech: "mladý / mladší / nejmladší", english: "young / younger / youngest", category: "adjectives" },
  { czech: "starý / starší / nejstarší", english: "old / older / oldest", category: "adjectives" },
  { czech: "lehký / lehčí / nejlehčí", english: "easy / easier / easiest", category: "adjectives" },
  { czech: "pruhovaný / pruhovaná / pruhované", english: "striped (m / f / n)", category: "adjectives" },
  { czech: "různý / různá / různé", english: "various / different (m / f / n)", category: "adjectives" },
  { czech: "spokojený / spokojená", english: "satisfied / content (m / f)", category: "adjectives" },
  { czech: "historický / historická / historické", english: "historic (m / f / n)", category: "adjectives" },
  { czech: "moderní", english: "modern (all genders)", category: "adjectives" },
  { czech: "mezinárodní", english: "international (all genders)", category: "adjectives" },
  { czech: "elegantní", english: "elegant (all genders)", category: "adjectives" },
  { czech: "chlupatý / chlupatá / chlupaté", english: "furry / hairy (m / f / n)", category: "adjectives" },
  // Verb aspect pairs (perfective / imperfective)
  { czech: "koupit / kupovat", english: "to buy — once / habitually", category: "aspect" },
  { czech: "přijít / přicházet", english: "to arrive (foot) — once / regularly", category: "aspect" },
  { czech: "odejít / odcházet", english: "to leave (foot) — once / regularly", category: "aspect" },
  { czech: "uvařit / vařit", english: "to cook — once / regularly", category: "aspect" },
  { czech: "napsat / psát", english: "to write — once / regularly", category: "aspect" },
  { czech: "přečíst / číst", english: "to read (through) — once / regularly", category: "aspect" },
  { czech: "udělat / dělat", english: "to do/make — once / regularly", category: "aspect" },
  { czech: "zavolat / volat", english: "to call — once / regularly", category: "aspect" },
  { czech: "dát / dávat", english: "to give — once / regularly", category: "aspect" },
  { czech: "říct / říkat", english: "to say — once / regularly", category: "aspect" },
  { czech: "vzít / brát", english: "to take — once / regularly", category: "aspect" },
  { czech: "podívat se / dívat se", english: "to have a look / to watch — once / regularly", category: "aspect" },
  { czech: "sníst / jíst", english: "to eat (up) — once / regularly", category: "aspect" },
  { czech: "vypít / pít", english: "to drink (up) — once / regularly", category: "aspect" },
  { czech: "oholit se / holit se", english: "to shave — once / regularly", category: "aspect" },
  { czech: "zaplatit / platit", english: "to pay — once / regularly", category: "aspect" },
  { czech: "zapomenout / zapomínat", english: "to forget — once / regularly", category: "aspect" },
  { czech: "vzpomenout si / vzpomínat si", english: "to remember — once / regularly", category: "aspect" },
  { czech: "usmát se / usmívat se", english: "to smile — once / regularly", category: "aspect" },
  { czech: "zavřít / zavírat", english: "to close — once / regularly", category: "aspect" },
  { czech: "přestat / přestávat", english: "to stop — once / regularly", category: "aspect" },
  { czech: "utratit / utrácet", english: "to spend money — once / regularly", category: "aspect" },
  // Connectors
  { czech: "ale", english: "but", category: "connectors" },
  { czech: "protože", english: "because", category: "connectors" },
  { czech: "proto", english: "therefore / that's why", category: "connectors" },
  { czech: "tak", english: "so / then", category: "connectors" },
  { czech: "když", english: "when / if", category: "connectors" },
  { czech: "že", english: "that (conjunction — myslím, že...)", category: "connectors" },
  { czech: "také / taky", english: "also / too", category: "connectors" },
  { czech: "nebo", english: "or", category: "connectors" },
  { czech: "ani", english: "nor / not even", category: "connectors" },
  { czech: "aby", english: "so that / in order to", category: "connectors" },
  { czech: "přestože", english: "although / even though", category: "connectors" },
  { czech: "pokud", english: "if / provided that", category: "connectors" },
  { czech: "než", english: "than / before (time)", category: "connectors" },
  { czech: "jak", english: "how / as / like", category: "connectors" },
  { czech: "a", english: "and", category: "connectors" },
  { czech: "proto že → protože", english: "that's why → because (common confusion)", category: "connectors" },
  { czech: "který / která / které", english: "which / who (m / f / n)", category: "connectors" },
  { czech: "skoro", english: "almost / nearly", category: "connectors" },
  // Negation
  { czech: "nikdy", english: "never", category: "negation" },
  { czech: "nic", english: "nothing", category: "negation" },
  { czech: "nikde", english: "nowhere (place)", category: "negation" },
  { czech: "nikam", english: "nowhere (direction)", category: "negation" },
  { czech: "nikdo", english: "nobody", category: "negation" },
  { czech: "žádný / žádná / žádné", english: "no / none / not any (m / f / n)", category: "negation" },
  { czech: "vůbec ne", english: "not at all", category: "negation" },
  { czech: "ne- (prefix)", english: "negates any verb: nejím, nevím, nejdu, nemám", category: "negation" },
  { czech: "nejím", english: "I don't eat", category: "negation" },
  { czech: "nevím", english: "I don't know", category: "negation" },
  { czech: "nejdu", english: "I'm not going", category: "negation" },
  { czech: "nemám", english: "I don't have", category: "negation" },
  { czech: "nechci", english: "I don't want", category: "negation" },
  { czech: "Nikdy nic nejím.", english: "I never eat anything. (double negation — correct in Czech)", category: "negation" },
  { czech: "Chtěl/a bych...", english: "I would like... (m / f) — polite request", category: "negation" },
];

const MATCHING_SETS = [
  {
    title: "Lesson 1 — Food & Health",
    pairs: [
      { q: "Co jste měli včera k večeři?", qen: "What did you have for dinner yesterday?", a: "Kuřecí kostky na kari a rýži.", aen: "Chicken pieces with curry and rice." },
      { q: "Kdy bude Martin zpátky?", qen: "When will Martin be back?", a: "Za 2 týdny.", aen: "In 2 weeks." },
      { q: "Máš rád polévky?", qen: "Do you like soups?", a: "Mám. Nejradši mám česneku.", aen: "I do. My favourite is garlic soup." },
      { q: "Bereš nějaké vitamíny?", qen: "Do you take any vitamins?", a: "Ano. Céčko a béčko.", aen: "Yes. Vitamin C and vitamin B." },
      { q: "Kde je Ivana?", qen: "Where is Ivana?", a: "Na masáži.", aen: "At a massage." },
      { q: "Bolí ho něco?", qen: "Does anything hurt him?", a: "Ne. Všechno je v pořádku.", aen: "No. Everything is fine." },
    ]
  },
  {
    title: "Lesson 2 — Questions & Places",
    pairs: [
      { q: "Bereš nějaké vitamíny?", qen: "Do you take any vitamins?", a: "Jo. Vitamín C a vitamín B12.", aen: "Yes. Vitamin C and vitamin B12." },
      { q: "Máš rád pažitku?", qen: "Do you like chives?", a: "Jo. Miluji chleba s máslem a pažitkou.", aen: "Yes. I love bread with butter and chives." },
      { q: "Jakou vaříš polévku?", qen: "What soup are you making?", a: "Česneku.", aen: "Garlic soup." },
      { q: "Kde jsi byl?", qen: "Where were you?", a: "Na masáži.", aen: "At a massage." },
      { q: "Kam jdeš?", qen: "Where are you going?", a: "Do knihovny.", aen: "To the library." },
      { q: "Jak dlouho jste byli pryč?", qen: "How long were you away?", a: "2 týdny.", aen: "2 weeks." },
      { q: "Kdy budeš doma?", qen: "When will you be home?", a: "V 18:45.", aen: "At 18:45." },
    ]
  },
  {
    title: "Lesson 3 — School & Doctor",
    pairs: [
      { q: "Kde je Milan?", qen: "Where is Milan?", a: "U doktora.", aen: "At the doctor's." },
      { q: "Kam jdeš?", qen: "Where are you going?", a: "K doktorovi.", aen: "To the doctor." },
      { q: "Napsal jsi ten dopis?", qen: "Did you write that letter?", a: "Ještě ne. Udělám to zítra.", aen: "Not yet. I'll do it tomorrow." },
      { q: "Nosí Ivan brýle?", qen: "Does Ivan wear glasses?", a: "Jo. Nosí. Na čtení.", aen: "Yes, he does. For reading." },
      { q: "Co bude k večeři?", qen: "What's for dinner?", a: "Sekaná a bramborová kaše.", aen: "Meatloaf and mashed potatoes." },
      { q: "Co teď čteš?", qen: "What are you reading now?", a: "Psychologický román.", aen: "A psychological novel." },
      { q: "Chodí Michal na základní školu?", qen: "Does Michal go to primary school?", a: "Na střední.", aen: "Secondary school." },
      { q: "Kdy přijedou vaši?", qen: "When will your parents arrive?", a: "23. 4.", aen: "23rd April." },
    ]
  },
  {
    title: "Lesson 4 — Watching TV",
    pairs: [
      { q: "Na co se díváš?", qen: "What are you watching?", a: "Na francouzskou komedii.", aen: "A French comedy." },
      { q: "Chceš se večer dívat na televizi?", qen: "Do you want to watch TV tonight?", a: "Dneska ne. Budu si číst.", aen: "Not tonight. I'll be reading." },
      { q: "Máme doma céčko?", qen: "Do we have vitamin C at home?", a: "Myslím, že ano. Podívám se.", aen: "I think so. I'll have a look." },
      { q: "Kde je Michal?", qen: "Where is Michal?", a: "U doktora.", aen: "At the doctor's." },
    ]
  },
  {
    title: "Lesson 5 — Health & Body",
    pairs: [
      { q: "Kde tě bolí?", qen: "Where does it hurt?", a: "Bolí mě záda.", aen: "My back hurts." },
      { q: "Co ti je?", qen: "What's the matter with you?", a: "Mám nachlazení.", aen: "I have a cold." },
      { q: "Jak se cítíš?", qen: "How do you feel?", a: "Cítím se špatně.", aen: "I feel unwell." },
      { q: "Byl jsi u doktora?", qen: "Did you go to the doctor?", a: "Ano. Dal mi recept.", aen: "Yes. He gave me a prescription." },
      { q: "Bereš nějaké léky?", qen: "Are you taking any medicine?", a: "Jo. Beru prášky na bolest.", aen: "Yes. I'm taking painkillers." },
      { q: "Kdy budeš zdravý?", qen: "When will you be better?", a: "Doufám, že brzy.", aen: "I hope soon." },
    ]
  },
  {
    title: "Lesson 6 — Restaurant & Food",
    pairs: [
      { q: "Máš hlad?", qen: "Are you hungry?", a: "Ano, mám. Kdy jíme?", aen: "Yes, I am. When do we eat?" },
      { q: "Co si dáš?", qen: "What will you have?", a: "Dám si kuřecí polévku.", aen: "I'll have chicken soup." },
      { q: "Jak chutná?", qen: "How does it taste?", a: "Je to výborné!", aen: "It's excellent!" },
      { q: "Je to moc ostré?", qen: "Is it too spicy?", a: "Ne, je to akorát.", aen: "No, it's just right." },
      { q: "Co doporučujete?", qen: "What do you recommend?", a: "Doporučuji grilovaná žebra.", aen: "I recommend grilled ribs." },
      { q: "Účet prosím.", qen: "The bill, please.", a: "Samozřejmě, hned.", aen: "Of course, right away." },
    ]
  },
  {
    title: "Lesson 7 — Past Tense",
    pairs: [
      { q: "Co jsi měl/a k obědu?", qen: "What did you have for lunch?", a: "Měl jsem kuřecí polévku.", aen: "I had chicken soup." },
      { q: "Kde jsi byl včera večer?", qen: "Where were you last night?", a: "Byl jsem v restauraci.", aen: "I was at a restaurant." },
      { q: "Viděl jsi ten film?", qen: "Did you see that film?", a: "Ne, ještě jsem ho neviděl.", aen: "No, I haven't seen it yet." },
      { q: "Kdy jsi přišel domů?", qen: "When did you come home?", a: "Přišel jsem ve 20:00.", aen: "I came home at 20:00." },
      { q: "Co jste dělali o víkendu?", qen: "What did you do at the weekend?", a: "Šli jsme na procházku.", aen: "We went for a walk." },
      { q: "Mluvil jsi česky?", qen: "Did you speak Czech?", a: "Ano, trochu jsem mluvil.", aen: "Yes, I spoke a little." },
    ]
  },
  {
    title: "Lesson 8 — Connectors & Negation",
    pairs: [
      { q: "Proč nejdeš do práce?", qen: "Why aren't you going to work?", a: "Protože jsem nemocný.", aen: "Because I'm ill." },
      { q: "Chceš kávu nebo čaj?", qen: "Do you want coffee or tea?", a: "Ani jedno, díky.", aen: "Neither, thanks." },
      { q: "Jíš maso?", qen: "Do you eat meat?", a: "Ne, nikdy nejím maso.", aen: "No, I never eat meat." },
      { q: "Víš, kde je Michal?", qen: "Do you know where Michal is?", a: "Nevím. Nikde ho nevidím.", aen: "I don't know. I can't see him anywhere." },
      { q: "Máš hlad?", qen: "Are you hungry?", a: "Vůbec ne. Právě jsem jedl.", aen: "Not at all. I've just eaten." },
      { q: "Proč to neuděláš?", qen: "Why won't you do it?", a: "Protože nemám čas.", aen: "Because I don't have time." },
    ]
  },
  {
    title: "Lesson 9 — Grooming & Hygiene",
    pairs: [
      { q: "Kdy se budeš holit?", qen: "When will you shave?", a: "Zítra. Teď jsem unavený.", aen: "Tomorrow. I'm tired now." },
      { q: "Proč si neumyješ vlasy?", qen: "Why don't you wash your hair?", a: "Mám je mastné. Umyji si je dnes ráno.", aen: "It's greasy. I'll wash it this morning." },
      { q: "Kde je Pavla?", qen: "Where is Pavla?", a: "Sprchuje se.", aen: "She's in the shower." },
      { q: "Jaký kartáček používáš?", qen: "What toothbrush do you use?", a: "Jenom měkký.", aen: "Only a soft one." },
      { q: "Jdu se sprchovat.", qen: "I'm going to have a shower.", a: "Osprchuji se a půjdu.", aen: "I'll have a shower and then go." },
    ]
  },
  {
    title: "Lesson 10 — Body, Directions & Exercise",
    pairs: [
      { q: "Jedete někam na dovolenou?", qen: "Are you going anywhere on holiday?", a: "Ano. Jako každý rok jedeme na jih.", aen: "Yes. As every year, we're going south." },
      { q: "Kde cvičí Irena?", qen: "Where does Irena exercise?", a: "V tělocvičně. Je tam pořád.", aen: "At the gym. She's always there." },
      { q: "Jdeš do tělocvičny?", qen: "Are you going to the gym?", a: "Ne. Radši jdu na velkou procházku nebo běhat.", aen: "No. I prefer a long walk or a run." },
      { q: "Kde je Karel?", qen: "Where is Karel?", a: "V koupelně. Šel se sprchovat.", aen: "In the bathroom. He went to shower." },
      { q: "Bolí ho pravá pata.", qen: "His right heel hurts.", a: "To je hrozné. Musí jít k doktorovi.", aen: "That's terrible. He must see a doctor." },
    ]
  },
  {
    title: "Lesson 11 — Appearance & Character",
    pairs: [
      { q: "Jejich syn má krásné modré oči.", qen: "Their son has beautiful blue eyes.", a: "Myslela jsem, že rodiče mají oba hnědé oči.", aen: "I thought both parents had brown eyes." },
      { q: "Ty jsi hezky opálená.", qen: "You're nicely tanned.", a: "Děkuji. Byli jsme týden kempovat.", aen: "Thank you. We went camping for a week." },
      { q: "Jak vypadá Marie?", qen: "What does Marie look like?", a: "Je elegantní, vysoká a štíhlá. Má hezký účes.", aen: "She's elegant, tall and slim. She has a nice hairstyle." },
      { q: "Ivan měl knír, ale minulý týden se oholil.", qen: "Ivan had a moustache, but he shaved last week.", a: "Škoda. Chtěl jsem vidět, jak vypadá s knírem.", aen: "What a shame. I wanted to see what he looks like with a moustache." },
      { q: "Dej mi pusu.", qen: "Give me a kiss.", a: "Dala mi velkou pusu.", aen: "She gave me a big kiss." },
    ]
  },
];

const CONJUGATIONS = [
  {
    verb: "dívat se",
    english: "to watch",
    forms: [
      { pronoun: "já", form: "dívám se", english: "I watch" },
      { pronoun: "ty", form: "díváš se", english: "you watch" },
      { pronoun: "on/ona", form: "dívá se", english: "he/she watches" },
      { pronoun: "my", form: "díváme se", english: "we watch" },
      { pronoun: "vy", form: "díváte se", english: "you (pl) watch" },
      { pronoun: "oni", form: "dívají se", english: "they watch" },
    ]
  },
  {
    verb: "brát",
    english: "to take",
    forms: [
      { pronoun: "já", form: "beru", english: "I take" },
      { pronoun: "ty", form: "bereš", english: "you take" },
      { pronoun: "on/ona", form: "bere", english: "he/she takes" },
      { pronoun: "my", form: "bereme", english: "we take" },
      { pronoun: "vy", form: "berete", english: "you (pl) take" },
      { pronoun: "oni", form: "berou", english: "they take" },
    ]
  },
  {
    verb: "jít",
    english: "to go (on foot)",
    forms: [
      { pronoun: "já", form: "jdu", english: "I go" },
      { pronoun: "ty", form: "jdeš", english: "you go" },
      { pronoun: "on/ona", form: "jde", english: "he/she goes" },
      { pronoun: "my", form: "jdeme", english: "we go" },
      { pronoun: "vy", form: "jdete", english: "you (pl) go" },
      { pronoun: "oni", form: "jdou", english: "they go" },
    ]
  },
  {
    verb: "mít",
    english: "to have",
    forms: [
      { pronoun: "já", form: "mám", english: "I have" },
      { pronoun: "ty", form: "máš", english: "you have" },
      { pronoun: "on/ona", form: "má", english: "he/she has" },
      { pronoun: "my", form: "máme", english: "we have" },
      { pronoun: "vy", form: "máte", english: "you (pl) have" },
      { pronoun: "oni", form: "mají", english: "they have" },
    ]
  },
  {
    verb: "chtít",
    english: "to want",
    forms: [
      { pronoun: "já", form: "chci", english: "I want" },
      { pronoun: "ty", form: "chceš", english: "you want" },
      { pronoun: "on/ona", form: "chce", english: "he/she wants" },
      { pronoun: "my", form: "chceme", english: "we want" },
      { pronoun: "vy", form: "chcete", english: "you (pl) want" },
      { pronoun: "oni", form: "chtějí", english: "they want" },
    ]
  },
  {
    verb: "jíst",
    english: "to eat",
    forms: [
      { pronoun: "já", form: "jím", english: "I eat" },
      { pronoun: "ty", form: "jíš", english: "you eat" },
      { pronoun: "on/ona", form: "jí", english: "he/she eats" },
      { pronoun: "my", form: "jíme", english: "we eat" },
      { pronoun: "vy", form: "jíte", english: "you (pl) eat" },
      { pronoun: "oni", form: "jedí", english: "they eat" },
    ]
  },
  {
    verb: "být",
    english: "to be (present)",
    forms: [
      { pronoun: "já", form: "jsem", english: "I am" },
      { pronoun: "ty", form: "jsi", english: "you are" },
      { pronoun: "on/ona", form: "je", english: "he/she is" },
      { pronoun: "my", form: "jsme", english: "we are" },
      { pronoun: "vy", form: "jste", english: "you (pl) are" },
      { pronoun: "oni", form: "jsou", english: "they are" },
    ]
  },
  {
    verb: "dělat — past tense (male speaker)",
    english: "to do / make (past, male)",
    forms: [
      { pronoun: "já", form: "dělal jsem", english: "I did / was doing" },
      { pronoun: "ty", form: "dělal jsi", english: "you did" },
      { pronoun: "on", form: "dělal", english: "he did (no auxiliary)" },
      { pronoun: "my", form: "dělali jsme", english: "we did" },
      { pronoun: "vy", form: "dělali jste", english: "you (pl) did" },
      { pronoun: "oni", form: "dělali", english: "they did (no auxiliary)" },
    ]
  },
  {
    verb: "dělat — past tense (female speaker)",
    english: "to do / make (past, female)",
    forms: [
      { pronoun: "já", form: "dělala jsem", english: "I did / was doing" },
      { pronoun: "ty", form: "dělala jsi", english: "you did" },
      { pronoun: "ona", form: "dělala", english: "she did (no auxiliary)" },
      { pronoun: "my", form: "dělaly jsme", english: "we did" },
      { pronoun: "vy", form: "dělaly jste", english: "you (pl) did" },
      { pronoun: "ony", form: "dělaly", english: "they did (no auxiliary)" },
    ]
  },
  {
    verb: "být — past tense",
    english: "to be (past)",
    forms: [
      { pronoun: "já (m)", form: "byl jsem", english: "I was (male)" },
      { pronoun: "já (f)", form: "byla jsem", english: "I was (female)" },
      { pronoun: "ty (m)", form: "byl jsi", english: "you were (male)" },
      { pronoun: "on/ona", form: "byl / byla", english: "he was / she was" },
      { pronoun: "my", form: "byli / byly jsme", english: "we were (m / f)" },
      { pronoun: "oni", form: "byli / byly", english: "they were (m / f)" },
    ]
  },
  {
    verb: "koupit",
    english: "to buy (once / future)",
    forms: [
      { pronoun: "já", form: "koupím", english: "I will buy" },
      { pronoun: "ty", form: "koupíš", english: "you will buy" },
      { pronoun: "on/ona", form: "koupí", english: "he/she will buy" },
      { pronoun: "my", form: "koupíme", english: "we will buy" },
      { pronoun: "vy", form: "koupíte", english: "you (pl) will buy" },
      { pronoun: "oni", form: "koupí", english: "they will buy" },
    ]
  },
  {
    verb: "opalovat se",
    english: "to sunbathe",
    forms: [
      { pronoun: "já", form: "opaluji se", english: "I sunbathe" },
      { pronoun: "ty", form: "opaluješ se", english: "you sunbathe" },
      { pronoun: "on/ona", form: "opaluje se", english: "he/she sunbathes" },
      { pronoun: "my", form: "opalujeme se", english: "we sunbathe" },
      { pronoun: "vy", form: "opalujete se", english: "you (pl) sunbathe" },
      { pronoun: "oni", form: "opalují se", english: "they sunbathe" },
    ]
  },
  {
    verb: "cvičit",
    english: "to exercise",
    forms: [
      { pronoun: "já", form: "cvičím", english: "I exercise" },
      { pronoun: "ty", form: "cvičíš", english: "you exercise" },
      { pronoun: "on/ona", form: "cvičí", english: "he/she exercises" },
      { pronoun: "my", form: "cvičíme", english: "we exercise" },
      { pronoun: "vy", form: "cvičíte", english: "you (pl) exercise" },
      { pronoun: "oni", form: "cvičí", english: "they exercise" },
    ]
  },
  {
    verb: "sedět",
    english: "to sit",
    forms: [
      { pronoun: "já", form: "sedím", english: "I sit" },
      { pronoun: "ty", form: "sedíš", english: "you sit" },
      { pronoun: "on/ona", form: "sedí", english: "he/she sits" },
      { pronoun: "my", form: "sedíme", english: "we sit" },
      { pronoun: "vy", form: "sedíte", english: "you (pl) sit" },
      { pronoun: "oni", form: "sedí", english: "they sit" },
    ]
  },
  {
    verb: "žít",
    english: "to live",
    forms: [
      { pronoun: "já", form: "žiji / žiju", english: "I live" },
      { pronoun: "ty", form: "žiješ", english: "you live" },
      { pronoun: "on/ona", form: "žije", english: "he/she lives" },
      { pronoun: "my", form: "žijeme", english: "we live" },
      { pronoun: "vy", form: "žijete", english: "you (pl) live" },
      { pronoun: "oni", form: "žijí / žijou", english: "they live" },
    ]
  },
  {
    verb: "říkat",
    english: "to say (regularly)",
    forms: [
      { pronoun: "já", form: "říkám", english: "I say" },
      { pronoun: "ty", form: "říkáš", english: "you say" },
      { pronoun: "on/ona", form: "říká", english: "he/she says" },
      { pronoun: "my", form: "říkáme", english: "we say" },
      { pronoun: "vy", form: "říkáte", english: "you (pl) say" },
      { pronoun: "oni", form: "říkají", english: "they say" },
    ]
  },
];
